In [1]:
%pip install matplotlib numpy pandas
import matplotlib.pyplot as plt 
import numpy as np 
import pandas as pd

Requirement already satisfied: matplotlib in c:\users\praet\appdata\local\python\pythoncore-3.14-64\lib\site-packages (3.10.8)
Requirement already satisfied: numpy in c:\users\praet\appdata\local\python\pythoncore-3.14-64\lib\site-packages (2.4.2)
Requirement already satisfied: pandas in c:\users\praet\appdata\local\python\pythoncore-3.14-64\lib\site-packages (3.0.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\praet\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\praet\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\praet\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\praet\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\praet\appdata\roaming\python\python314\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\praet\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\praet\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\praet\appdata\roaming\python\python314\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\praet\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\praet\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
df_1 = pd.read_csv('../fbref_2023-2024_Domestic_Leagues_stats.csv')

df_2 = pd.read_csv('../fbref_2024_2025_Domestic_League_stats.csv')

In [3]:
df_1.head(25)

,Rk,Player,Gls/90,SoT/90,Sh/90,G/Sh,G/SoT,TklW/90,Int/90,Season,...,Int/90.1,Tkl+Int,Sh/90.1,G/Sh.1,G/SoT.1,SoT/90.1,SoT%,FK,Pos,-9999
0,1,Macaulay Langstaff,0.6,1.5,3.8,0.14,0.35,0.2,0.2,2023-2024,...,0.2,0.0,3.8,0.14,0.35,1.5,40.1,NaN,FWMF,ca9b48af
1,2,Sammie Szmodics,0.6,1.4,3.3,0.19,0.46,0.4,0.4,2023-2024,...,0.4,0.0,3.3,0.19,0.46,1.4,41.3,NaN,MFFW,39944392
2,3,Matt Smith,0.6,1.4,3.1,0.20,0.43,0.1,0.1,2023-2024,...,0.1,0.0,3.1,0.20,0.43,1.4,45.5,NaN,FW,2d44ca9b
3,4,Alfie May,0.6,1.4,3.7,0.12,0.32,0.4,0.1,2023-2024,...,0.1,0.0,3.7,0.12,0.32,1.4,36.8,NaN,FWMF,992453d1
4,5,Davis Keillor-Dunn,0.6,1.8,4.3,0.13,0.33,0.9,0.6,2023-2024,...,0.6,0.0,4.3,0.13,0.33,1.8,41.1,NaN,MFFW,41d05caa
5,6,Kévin Denkey,0.7,1.5,4.2,0.15,0.43,0.4,0.1,2023-2024,...,0.1,0.0,4.2,0.15,0.43,1.5,35.4,NaN,FW,0d3585b5
6,7,Martin Braithwaite,0.6,1.2,3.0,0.14,0.35,0.3,0.1,2023-2024,...,0.1,0.0,3.0,0.14,0.35,1.2,39.1,NaN,FW,fd771f95
7,8,Henk Veerman,0.6,1.4,3.0,0.18,0.40,0.2,0.1,2023-2024,...,0.1,0.0,3.0,0.18,0.40,1.4,45.5,NaN,FW,e1a1b481
8,9,Lawrence Shankland,0.7,1.4,3.8,0.15,0.42,0.3,0.1,2023-2024,...,0.1,0.0,3.8,0.15,0.42,1.4,36.8,NaN,FW,63b1a176
9,10,Alexandre Mendy,0.6,1.3,2.8,0.17,0.36,0.1,0.2,2023-2024,...,0.2,0.0,2.8,0.17,0.36,1.3,47.5,NaN,FW,e067808c
10,11,Paul Mullin,0.7,1.6,3.4,0.18,0.38,0.5,0.2,2023-2024,...,0.2,0.0,3.4,0.18,0.38,1.6,47.3,NaN,FW,e7ef2c4e
11,12,Vangelis Pavlidis,0.9,1.9,3.6,0.23,0.45,0.6,0.1,2023-2024,...,0.1,0.0,3.6,0.23,0.45,1.9,51.2,NaN,FW,d578db11
12,13,Milan Smit,0.6,1.3,2.7,0.12,0.26,0.8,0.3,2023-2024,...,0.3,0.0,2.7,0.12,0.26,1.3,47.8,NaN,FWMF,a61ff812
13,14,Anders Dreyer,0.6,1.3,2.9,0.17,0.37,0.4,0.3,2023-2024,...,0.3,0.0,2.9,0.17,0.37,1.3,45.3,NaN,FWMF,c6486b01
14,15,Viktor Gyökeres,0.9,1.8,3.5,0.21,0.41,0.3,0.2,2023-2024,...,0.2,0.0,3.5,0.21,0.41,1.8,51.3,NaN,FW,4d5a9185
15,16,Phil Foden,0.6,1.5,3.3,0.18,0.40,0.6,0.4,2023-2024,...,0.4,0.0,3.3,0.18,0.40,1.5,45.7,NaN,MF,ed1e53f3
16,17,Mauro Icardi,0.8,1.6,3.5,0.17,0.38,0.1,0.1,2023-2024,...,0.1,0.0,3.5,0.17,0.38,1.6,44.6,NaN,FW,43b78598
17,18,Isaac Olaofe,0.6,1.0,2.2,0.29,0.61,0.5,0.1,2023-2024,...,0.1,0.0,2.2,0.29,0.61,1.0,48.5,NaN,FW,2f4fb18c
18,19,Harry Kane,1.1,2.1,4.6,0.21,0.46,0.3,0.3,2023-2024,...,0.3,0.0,4.6,0.21,0.46,2.1,45.9,NaN,FW,21a66f6a
19,20,Philip Otele,0.6,1.6,3.2,0.18,0.37,0.7,0.6,2023-2024,...,0.6,0.0,3.2,0.18,0.37,1.6,49.0,NaN,FWMF,d3655d19
20,21,Peque,0.6,1.1,2.2,0.14,0.28,1.1,0.3,2023-2024,...,0.3,0.0,2.2,0.14,0.28,1.1,52.2,NaN,MF,cb971b4f
21,22,Gennaro Tutino,0.6,1.3,2.9,0.18,0.41,0.1,0.0,2023-2024,...,0.0,0.0,2.9,0.18,0.41,1.3,42.9,NaN,FWMF,8b303bcb
22,23,Luuk de Jong,0.9,2.1,4.7,0.16,0.37,0.5,0.1,2023-2024,...,0.1,0.0,4.7,0.16,0.37,2.1,43.4,NaN,FW,abb3bb95
23,24,Robert Lewandowski,0.6,1.4,3.0,0.16,0.35,0.1,0.3,2023-2024,...,0.3,0.0,3.0,0.16,0.35,1.4,46.2,NaN,FW,8d78e732
24,25,Edin Džeko,0.7,2.1,4.9,0.13,0.30,0.4,0.1,2023-2024,...,0.1,0.0,4.9,0.13,0.30,2.1,43.5,NaN,FW,3bb7f478

In [4]:
df_2.head(25)

,Rk,Player,Min,SoT/90,Sh/90,G/Sh,G/SoT,TklW/90,Int/90,Season,...,Int/90.1,Tkl+Int,Sh/90.1,G/Sh.1,G/SoT.1,SoT/90.1,SoT%,FK,Pos,-9999
0,1,James Wilson,4140,0.1,0.3,0.14,0.40,1.3,1.9,2024-2025,...,1.9,0.0,0.3,0.14,0.40,0.1,35.7,NaN,DF,77621175
1,2,Sean Roughan,4140,0.1,0.4,0.06,0.17,1.0,1.0,2024-2025,...,1.0,0.0,0.4,0.06,0.17,0.1,33.3,NaN,DF,a8100b7e
2,3,Zak Vyner,4140,0.0,0.3,0.07,1.00,1.1,0.9,2024-2025,...,0.9,0.0,0.3,0.07,1.00,0.0,6.7,NaN,DF,a8fe5a96
3,4,Jason Knight,4140,0.2,1.1,0.06,0.33,0.9,1.0,2024-2025,...,1.0,0.0,1.1,0.06,0.33,0.2,18.4,NaN,MF,b83ec960
4,5,Lewis Wing,4140,0.5,2.0,0.10,0.38,1.8,1.0,2024-2025,...,1.0,0.0,2.0,0.10,0.38,0.5,26.1,NaN,MF,c2cba4c3
5,6,Dominic Hyam,4140,0.1,0.5,0.10,0.67,0.6,0.6,2024-2025,...,0.6,0.0,0.5,0.10,0.67,0.1,14.3,NaN,DF,ce95958a
6,7,Joe Rodon,4135,0.0,0.5,0.05,0.50,0.5,0.7,2024-2025,...,0.7,0.0,0.5,0.05,0.50,0.0,9.5,NaN,DF,8d62d31a
7,8,Owen Bailey,4123,0.3,1.2,0.09,0.36,0.9,0.8,2024-2025,...,0.8,0.0,1.2,0.09,0.36,0.3,26.4,NaN,MFDF,dee69b15
8,9,Josh Neufville,4059,0.3,0.8,0.11,0.33,1.1,0.7,2024-2025,...,0.7,0.0,0.8,0.11,0.33,0.3,31.6,NaN,MF,3ea4f2f3
9,10,Will Wright,4057,0.3,0.8,0.16,0.40,0.8,1.0,2024-2025,...,1.0,0.0,0.8,0.16,0.40,0.3,39.5,NaN,DF,23c09e2b
10,11,Maxime Estève,4055,0.0,0.2,0.14,1.00,0.6,0.9,2024-2025,...,0.9,0.0,0.2,0.14,1.00,0.0,14.3,NaN,DF,1a066e69
11,12,Jimmy Dunne,4050,0.4,1.2,0.09,0.26,1.6,1.0,2024-2025,...,1.0,0.0,1.2,0.09,0.26,0.4,34.5,NaN,DF,1fdfd6da
12,13,Paul Nardi,4050,0.0,0.0,0.00,0.00,0.0,0.0,2024-2025,...,0.0,0.0,0.0,0.00,0.00,0.0,100.0,NaN,GK,2d70dbe5
13,14,Anthony O'Connor,4050,0.1,0.5,0.04,0.20,0.8,1.4,2024-2025,...,1.4,0.0,0.5,0.04,0.20,0.1,21.7,NaN,DF,d2d32944
14,15,Matthew Platt,4050,0.2,0.4,0.11,0.29,1.0,0.8,2024-2025,...,0.8,0.0,0.4,0.11,0.29,0.2,36.8,NaN,DF,d3504afe
15,16,Shane Duffy,4040,0.2,0.8,0.11,0.44,0.4,0.7,2024-2025,...,0.7,0.0,0.8,0.11,0.44,0.2,25.0,NaN,DF,7314bba4
16,17,Ben Cabango,4032,0.1,0.5,0.09,0.40,1.3,0.9,2024-2025,...,0.9,0.0,0.5,0.09,0.40,0.1,21.7,NaN,DF,70723cac
17,18,Connor Ogilvie,4028,0.2,0.9,0.10,0.44,0.6,1.4,2024-2025,...,1.4,0.0,0.9,0.10,0.44,0.2,23.1,NaN,DF,c096c77f
18,19,Milan van Ewijk,4010,0.2,0.7,0.07,0.25,1.6,1.3,2024-2025,...,1.3,0.0,0.7,0.07,0.25,0.2,27.6,NaN,DFMF,58448fbb
19,20,Torbjørn Heggem,4010,0.1,0.6,0.04,0.17,1.1,0.7,2024-2025,...,0.7,0.0,0.6,0.04,0.17,0.1,23.1,NaN,DF,834fea76
20,21,Alistair Smith,4006,0.5,1.4,0.10,0.29,1.1,0.7,2024-2025,...,0.7,0.0,1.4,0.10,0.29,0.5,33.9,NaN,MF,0eae7a49
21,22,Matt Grimes,3976,0.2,0.6,0.11,0.33,1.0,0.8,2024-2025,...,0.8,0.0,0.6,0.11,0.33,0.2,32.1,NaN,MF,81a487b9
22,23,Joe Powell,3964,0.2,1.4,0.02,0.09,1.0,1.0,2024-2025,...,1.0,0.0,1.4,0.02,0.09,0.2,17.7,NaN,MF,a0961a90
23,24,Jason Kerr,3960,0.1,0.4,0.06,0.33,0.5,1.4,2024-2025,...,1.4,0.0,0.4,0.06,0.33,0.1,17.6,NaN,DF,b9fc65bc
24,25,Connor Hall,3956,0.2,0.8,0.00,0.00,1.0,1.3,2024-2025,...,1.3,0.0,0.8,0.00,0.00,0.2,25.7,NaN,DF,9f0a817d

In [5]:
df_1.drop(columns=['Rk','Season', 'FK', '-9999'], inplace=True)
df_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 7170 entries, 0 to 7169
Data columns (total 34 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Player     7170 non-null   str
 1   Gls/90     7170 non-null   float64
 2   SoT/90     7170 non-null   float64
 3   Sh/90      7170 non-null   float64
 4   G/Sh       7170 non-null   float64
 5   G/SoT      7170 non-null   float64
 6   TklW/90    7170 non-null   float64
 7   Int/90     7170 non-null   float64
 8   Age        7166 non-null   float64
 9   Nation     7151 non-null   str
 10  Team       7170 non-null   str
 11  Comp       7170 non-null   str
 12  MP         7170 non-null   int64
 13  Min▼       7170 non-null   int64
 14  90s        7170 non-null   float64
 15  Starts     7170 non-null   int64
 16  Subs       7170 non-null   int64
 17  unSub      7170 non-null   int64
 18  Gls/90.1   7170 non-null   float64
 19  Ast        7170 non-null   float64
 20  G+A        7170 non-null   float64
 21  G-PK       7170 non-null   float64
 22  PK         7170 non-null   float64
 23  PKatt      7170 non-null   float64
 24  PKm        7170 non-null   float64
 25  TklW/90.1  7170 non-null   float64
 26  Int/90.1   7170 non-null   float64
 27  Tkl+Int    7170 non-null   float64
 28  Sh/90.1    7170 non-null   float64
 29  G/Sh.1     7170 non-null   float64
 30  G/SoT.1    7170 non-null   float64
 31  SoT/90.1   7170 non-null   float64
 32  SoT%       7170 non-null   float64
 33  Pos        7170 non-null   str
dtypes: float64(24), int64(5), str(5)
memory usage: 1.9 MB

In [6]:
# Clean up Nation column - convert codes like 'eng ENG' to 'England'
import re

# Extract the 3-letter country code (uppercase part) from Nation column
def clean_nation(nation_str):
    if pd.isna(nation_str):
        return nation_str
    # Extract the uppercase 3-letter code
    match = re.search(r'\b([A-Z]{3})\b', str(nation_str))
    code = match.group(1) if match else None
    
    if not code:
        return nation_str
    
    # Country code to name mapping (common FIFA/ISO codes)
    country_mapping = {
        'ENG': 'England', 'FRA': 'France', 'ESP': 'Spain', 'GER': 'Germany',
        'ITA': 'Italy', 'POR': 'Portugal', 'NED': 'Netherlands', 'BEL': 'Belgium',
        'ARG': 'Argentina', 'BRA': 'Brazil', 'URU': 'Uruguay', 'COL': 'Colombia',
        'CHI': 'Chile', 'MEX': 'Mexico', 'USA': 'United States', 'CAN': 'Canada',
        'CRO': 'Croatia', 'SRB': 'Serbia', 'SUI': 'Switzerland', 'AUT': 'Austria',
        'DEN': 'Denmark', 'SWE': 'Sweden', 'NOR': 'Norway', 'POL': 'Poland',
        'CZE': 'Czech Republic', 'SCO': 'Scotland', 'WAL': 'Wales', 'NIR': 'Northern Ireland',
        'IRL': 'Republic of Ireland', 'TUR': 'Turkey', 'GRE': 'Greece', 'UKR': 'Ukraine',
        'ROU': 'Romania', 'SVK': 'Slovakia', 'SVN': 'Slovenia', 'BUL': 'Bulgaria',
        'JPN': 'Japan', 'KOR': 'South Korea', 'AUS': 'Australia', 'NZL': 'New Zealand',
        'MAR': 'Morocco', 'SEN': 'Senegal', 'NGA': 'Nigeria', 'CIV': 'Ivory Coast',
        'GHA': 'Ghana', 'CMR': 'Cameroon', 'ALG': 'Algeria', 'TUN': 'Tunisia',
        'EGY': 'Egypt', 'RSA': 'South Africa', 'PAR': 'Paraguay', 'ECU': 'Ecuador',
        'VEN': 'Venezuela', 'PER': 'Peru', 'BOL': 'Bolivia', 'CRC': 'Costa Rica',
        'HON': 'Honduras', 'PAN': 'Panama', 'JAM': 'Jamaica', 'ISL': 'Iceland',
        'FIN': 'Finland', 'HUN': 'Hungary', 'BIH': 'Bosnia and Herzegovina',
        'MKD': 'North Macedonia', 'ALB': 'Albania', 'GEO': 'Georgia', 'ARM': 'Armenia',
        'ISR': 'Israel', 'CHN': 'China', 'IRN': 'Iran', 'KSA': 'Saudi Arabia',
        'QAT': 'Qatar', 'UAE': 'United Arab Emirates', 'IRQ': 'Iraq', 'UZB': 'Uzbekistan',
        'ATG': 'Antigua and Barbuda', 'BHR': 'Bahrain', 'BRN': 'Brunei', 'CYM': 'Cayman Islands',
        'DMA': 'Dominica', 'FRO': 'Faroe Islands', 'GIB': 'Gibraltar', 'GRL': 'Greenland', 'GUY': 'Guyana',
        'LIE': 'Liechtenstein', 'MDV': 'Maldives', 'MNE': 'Montenegro', 'MSR': 'Montserrat', 'NCL': 'New Caledonia',
        'PYF': 'French Polynesia', 'SMR': 'San Marino', 'TGO': 'Togo', 'TON': 'Tonga', 'VAT': 'Vatican City',
        'ANG': 'Angola', 'BDI': 'Burundi', 'BEN': 'Benin', 'BFA': 'Burkina Faso', 'CTA': 'Central African Republic',
        'CGO': 'Congo', 'COM': 'Comoros', 'DJI': 'Djibouti', 'ERI': 'Eritrea', 'ETH': 'Ethiopia',
        'GAB': 'Gabon', 'GMB': 'Gambia', 'GAM': 'Gambia', 'GIN': 'Guinea', 'GUI': 'Guinea', 'GNB': 'Guinea-Bissau', 'KEN': 'Kenya', 'LES': 'Lesotho', 'LBR': 'Liberia', 'MDV': 'Maldives',
        'MLI': 'Mali', 'MOZ': 'Mozambique', 'NAM': 'Namibia', 'NER': 'Niger', 'RWA': 'Rwanda',
        'SLE': 'Sierra Leone', 'SOM': 'Somalia', 'SSD': 'South Sudan', 'STP': 'Sao Tome and Principe', 
        'SWZ': 'Eswatini', 'TCD': 'Chad', 'TUN': 'Tunisia', 'UGA': 'Uganda', 'ZAM': 'Zambia', 'ZIM': 'Zimbabwe',
        'BLR': 'Belarus', 'BLZ': 'Belize', 'BOL': 'Bolivia', 'BOS': 'Bosnia and Herzegovina',
        'BEN': 'Benin', 'COD': 'DR Congo', 'BOE': 'Bonaire, Sint Eustatius and Saba', 'CUB': 'Cuba',
        'CPV': 'Cape Verde', 'DOM': 'Dominican Republic', 'GUF': 'French Guiana', 'CUW': 'Curacao', 
        'LBN': 'Lebanon', 'MYS': 'Malaysia', 'MDV': 'Maldives', 'MRT': 'Mauritania',
        'EST': 'Estonia', 'LTU': 'Lithuania', 'LVA': 'Latvia', 'RUS': 'Russia', 'CYP': 'Cyprus', 'LUX': 'Luxembourg', 'MDA': 'Moldova',
        'GRN': 'Grenada', 'GUA': 'Guatemala', 'HTI': 'Haiti', 'NIC': 'Nicaragua', 'IDN': 'Indonesia', 'IND': 'India', 'PAK': 'Pakistan', 'PHL': 'Philippines', 'THA': 'Thailand',
        'JOR': 'Jordan', 'KAZ': 'Kazakhstan', 'KGZ': 'Kyrgyzstan', 'LAO': 'Laos', 'LBN': 'Lebanon', 'MMR': 'Myanmar', 'NEP': 'Nepal', 'OMN': 'Oman',
        'KEN': 'Kenya', 'RWA': 'Rwanda', 'SLE': 'Sierra Leone', 'SOM': 'Somalia', 'SSD': 'South Sudan', 'STP': 'Sao Tome and Principe', 'LBY': 'Libya', 
        'SKN': 'Saint Kitts and Nevis', 'LCA': 'Saint Lucia', 'VCT': 'Saint Vincent and the Grenadines', 'SUR': 'Suriname', 'TTO': 'Trinidad and Tobago', 'TRI': 'Trinidad and Tobago',
        'LBR': 'Liberia', 'LIB': 'Lebanon', 'MAD': 'Madagascar', 'MLI': 'Mali', 'MOZ': 'Mozambique', 'NAM': 'Namibia', 'NER': 'Niger', 'RWA': 'Rwanda',
        'MTQ': 'Martinique', 'MUS': 'Mauritius', 'MYA': 'Myanmar', 'PYF': 'French Polynesia', 'REU': 'Reunion', 'SPM': 'Saint Pierre and Miquelon', 
        'VAN': 'Vanuatu', 'WSM': 'Samoa', 'YEM': 'Yemen', 'MSR': 'Montserrat', 'MLT': 'Malta', 'MAS': 'Malaysia', 'TOG': 'Togo', 'GLP': 'Guadeloupe',
        'EQG': 'Equatorial Guinea', 'HAI': 'Haiti', 'SRI': 'Sri Lanka', 'MTN': 'Mauritania', 'NIG': 'Niger', 'PHI': 'Phillipines', 'PLE': 'Palestine',
        'SDN': 'Sudan', 'SMA': 'Sint Maarten', 'CHA': 'Chad', 'TOG': 'Togo', 'VIE': 'Vietnam', 'KVX': 'Kosovo', 'AZE': 'Azerbaijan', 'BER': 'Bermuda', 'BAN': 'Bangladesh', 'FIJ': 'Fiji',
        'TAN': 'Tanzania', 'SYR': 'Syria', 'TCH': 'Czechia', 'MWI': 'Malawi', 'BRB': 'Barbados'
    } 
    
    return country_mapping.get(code, nation_str)

# Apply to dataframe
if 'Nation' in df_1.columns:
    df_1['Nation'] = df_1['Nation'].apply(clean_nation)

if 'Nation' in df_2.columns:
    df_2['Nation'] = df_2['Nation'].apply(clean_nation)

print("Nation column cleaned successfully!")
print("\nSample values from df_1:")
print(df_1['Nation'].value_counts().head(10))

Nation column cleaned successfully!

Sample values from df_1:
Nation
England        832
Spain          532
France         438
Netherlands    382
Italy          334
Germany        334
Brazil         235
Portugal       181
Belgium        167
Croatia        165
Name: count, dtype: int64

In [7]:
df_1.head(50)

,Player,Gls/90,SoT/90,Sh/90,G/Sh,G/SoT,TklW/90,Int/90,Age,Nation,...,PKm,TklW/90.1,Int/90.1,Tkl+Int,Sh/90.1,G/Sh.1,G/SoT.1,SoT/90.1,SoT%,Pos
0,Macaulay Langstaff,0.6,1.5,3.8,0.14,0.35,0.2,0.2,26.0,England,...,0.0,0.2,0.2,0.0,3.8,0.14,0.35,1.5,40.1,FWMF
1,Sammie Szmodics,0.6,1.4,3.3,0.19,0.46,0.4,0.4,27.0,Republic of Ireland,...,0.0,0.4,0.4,0.0,3.3,0.19,0.46,1.4,41.3,MFFW
2,Matt Smith,0.6,1.4,3.1,0.20,0.43,0.1,0.1,34.0,England,...,0.0,0.1,0.1,0.0,3.1,0.20,0.43,1.4,45.5,FW
3,Alfie May,0.6,1.4,3.7,0.12,0.32,0.4,0.1,30.0,England,...,0.0,0.4,0.1,0.0,3.7,0.12,0.32,1.4,36.8,FWMF
4,Davis Keillor-Dunn,0.6,1.8,4.3,0.13,0.33,0.9,0.6,25.0,England,...,0.0,0.9,0.6,0.0,4.3,0.13,0.33,1.8,41.1,MFFW
5,Kévin Denkey,0.7,1.5,4.2,0.15,0.43,0.4,0.1,22.0,Togo,...,0.0,0.4,0.1,0.0,4.2,0.15,0.43,1.5,35.4,FW
6,Martin Braithwaite,0.6,1.2,3.0,0.14,0.35,0.3,0.1,32.0,Denmark,...,0.0,0.3,0.1,0.0,3.0,0.14,0.35,1.2,39.1,FW
7,Henk Veerman,0.6,1.4,3.0,0.18,0.40,0.2,0.1,30.0,Netherlands,...,0.0,0.2,0.1,0.0,3.0,0.18,0.40,1.4,45.5,FW
8,Lawrence Shankland,0.7,1.4,3.8,0.15,0.42,0.3,0.1,27.0,Scotland,...,0.1,0.3,0.1,0.0,3.8,0.15,0.42,1.4,36.8,FW
9,Alexandre Mendy,0.6,1.3,2.8,0.17,0.36,0.1,0.2,29.0,Guinea-Bissau,...,0.0,0.1,0.2,0.0,2.8,0.17,0.36,1.3,47.5,FW
10,Paul Mullin,0.7,1.6,3.4,0.18,0.38,0.5,0.2,28.0,England,...,0.0,0.5,0.2,0.0,3.4,0.18,0.38,1.6,47.3,FW
11,Vangelis Pavlidis,0.9,1.9,3.6,0.23,0.45,0.6,0.1,24.0,Greece,...,0.0,0.6,0.1,0.0,3.6,0.23,0.45,1.9,51.2,FW
12,Milan Smit,0.6,1.3,2.7,0.12,0.26,0.8,0.3,20.0,Netherlands,...,0.0,0.8,0.3,0.0,2.7,0.12,0.26,1.3,47.8,FWMF
13,Anders Dreyer,0.6,1.3,2.9,0.17,0.37,0.4,0.3,25.0,Denmark,...,0.0,0.4,0.3,0.0,2.9,0.17,0.37,1.3,45.3,FWMF
14,Viktor Gyökeres,0.9,1.8,3.5,0.21,0.41,0.3,0.2,25.0,Sweden,...,0.0,0.3,0.2,0.0,3.5,0.21,0.41,1.8,51.3,FW
15,Phil Foden,0.6,1.5,3.3,0.18,0.40,0.6,0.4,23.0,England,...,0.0,0.6,0.4,0.0,3.3,0.18,0.40,1.5,45.7,MF
16,Mauro Icardi,0.8,1.6,3.5,0.17,0.38,0.1,0.1,30.0,Argentina,...,0.0,0.1,0.1,0.0,3.5,0.17,0.38,1.6,44.6,FW
17,Isaac Olaofe,0.6,1.0,2.2,0.29,0.61,0.5,0.1,23.0,England,...,0.0,0.5,0.1,0.0,2.2,0.29,0.61,1.0,48.5,FW
18,Harry Kane,1.1,2.1,4.6,0.21,0.46,0.3,0.3,30.0,England,...,0.0,0.3,0.3,0.0,4.6,0.21,0.46,2.1,45.9,FW
19,Philip Otele,0.6,1.6,3.2,0.18,0.37,0.7,0.6,24.0,Nigeria,...,0.0,0.7,0.6,0.0,3.2,0.18,0.37,1.6,49.0,FWMF
20,Peque,0.6,1.1,2.2,0.14,0.28,1.1,0.3,20.0,Spain,...,0.0,1.1,0.3,0.0,2.2,0.14,0.28,1.1,52.2,MF
21,Gennaro Tutino,0.6,1.3,2.9,0.18,0.41,0.1,0.0,26.0,Italy,...,0.0,0.1,0.0,0.0,2.9,0.18,0.41,1.3,42.9,FWMF
22,Luuk de Jong,0.9,2.1,4.7,0.16,0.37,0.5,0.1,32.0,Netherlands,...,0.1,0.5,0.1,0.0,4.7,0.16,0.37,2.1,43.4,FW
23,Robert Lewandowski,0.6,1.4,3.0,0.16,0.35,0.1,0.3,34.0,Poland,...,0.0,0.1,0.3,0.0,3.0,0.16,0.35,1.4,46.2,FW
24,Edin Džeko,0.7,2.1,4.9,0.13,0.30,0.4,0.1,37.0,Bosnia and Herzegovina,...,0.0,0.4,0.1,0.0,4.9,0.13,0.30,2.1,43.5,FW
25,Joel Pohjanpalo,0.7,1.4,3.2,0.19,0.43,0.2,0.1,28.0,Finland,...,0.0,0.2,0.1,0.0,3.2,0.19,0.43,1.4,44.2,FW
26,Loïs Openda,0.8,2.1,4.0,0.18,0.35,0.1,0.1,23.0,Belgium,...,0.0,0.1,0.1,0.0,4.0,0.18,0.35,2.1,51.2,FW
27,Krzysztof Piątek,0.6,1.5,3.4,0.13,0.30,0.3,0.2,28.0,Poland,...,0.0,0.3,0.2,0.0,3.4,0.13,0.30,1.5,43.6,FW
28,Fashion Sakala,0.6,1.4,3.5,0.16,0.40,0.4,0.2,26.0,Zambia,...,0.0,0.4,0.2,0.0,3.5,0.16,0.40,1.4,40.0,FWMF
29,Lautaro Martínez,0.8,1.6,3.7,0.20,0.47,0.5,0.6,25.0,Argentina,...,0.0,0.5,0.6,0.0,3.7,0.20,0.47,1.6,43.1,FW
30,Cristiano Ronaldo,1.2,2.4,6.2,0.15,0.38,0.2,0.0,38.0,Portugal,...,0.0,0.2,0.0,0.0,6.2,0.15,0.38,2.4,39.8,FW
31,Robert Glatzel,0.7,1.6,3.6,0.19,0.42,0.3,0.1,29.0,Germany,...,0.0,0.3,0.1,0.0,3.6,0.19,0.42,1.6,45.7,FW
32,Haris Tabakovic,0.7,1.6,3.2,0.19,0.38,0.2,0.1,29.0,Bosnia and Herzegovina,...,0.0,0.2,0.1,0.0,3.2,0.19,0.38,1.6,50.5,FW
33,Jonathan David,0.7,1.6,2.7,0.22,0.36,0.6,0.3,23.0,Canada,...,0.0,0.6,0.3,0.0,2.7,0.22,0.36,1.6,59.5,FW
34,Pierre-Emerick Aubameyang,0.6,1.8,4.0,0.11,0.25,0.5,0.3,34.0,Gabon,...,0.0,0.5,0.3,0.0,4.0,0.11,0.25,1.8,44.0,FW
35,Cole Palmer,0.8,1.6,3.7,0.12,0.28,0.4,0.7,21.0,England,...,0.0,0.4,0.7,0.0,3.7,0.12,0.28,1.6,42.6,MFFW
36,Artem Dovbyk,0.8,1.6,3.0,0.20,0.37,0.1,0.0,26.0,Ukraine,...,0.0,0.1,0.0,0.0,3.0,0.20,0.37,1.6,54.1,FW
37,Florinel Coman,0.6,2.4,4.2,0.12,0.22,0.3,0.2,25.0,Romania,...,0.0,0.3,0.2,0.0,4.2,0.12,0.22,2.4,56.2,FWMF
38,Erling Haaland,1.0,2.1,4.3,0.17,0.34,0.1,0.1,23.0,Norway,...,0.0,0.1,0.1,0.0,4.3,0.17,0.34,2.1,48.8,FWMF
39,Mohamed Salah,0.6,2.0,4.0,0.11,0.23,0.4,0.1,31.0,Egypt,...,0.1,0.4,0.1,0.0,4.0,0.11,0.23,2.0,49.1,FW
40,Rafa Mújica,0.7,1.9,4.2,0.17,0.38,0.5,0.2,24.0,Spain,...,0.0,0.5,0.2,0.0,4.2,0.17,0.38,1.9,44.9,FW
41,Thiago,0.6,1.1,2.8,0.15,0.38,0.7,0.2,22.0,Brazil,...,0.0,0.7,0.2,0.0,2.8,0.15,0.38,1.1,41.0,FW
42,Guillermo Martínez Ayala,0.6,1.3,3.0,0.17,0.38,0.1,0.0,28.0,Mexico,...,0.0,0.1,0.0,0.0,3.0,0.17,0.38,1.3,44.0,FW
43,Rey Manaj,0.6,1.5,4.1,0.12,0.33,0.3,0.1,26.0,Albania,...,0.0,0.3,0.1,0.0,4.1,0.12,0.33,1.5,36.8,FW
44,Firas Al-Buraikan,0.6,0.9,1.7,0.35,0.62,0.7,0.3,23.0,Saudi Arabia,...,0.0,0.7,0.3,0.0,1.7,0.35,0.62,0.9,56.5,FW
45,Paddy Madden,0.6,1.5,3.0,0.16,0.32,0.3,0.2,33.0,Republic of Ireland,...,0.0,0.3,0.2,0.0,3.0,0.16,0.32,1.5,50.0,FWMF
46,Alexander Sørloth,0.8,1.3,2.8,0.29,0.64,0.1,0.0,27.0,Norway,...,0.0,0.1,0.0,0.0,2.8,0.29,0.64,1.3,46.2,FW
47,Ante Budimir,0.6,1.3,2.8,0.18,0.40,0.5,0.2,32.0,Croatia,...,0.0,0.5,0.2,0.0,2.8,0.18,0.40,1.3,46.1,FW
48,Jeredy Hilterman,0.6,1.6,3.4,0.16,0.36,0.7,0.4,25.0,Suriname,...,0.0,0.7,0.4,0.0,3.4,0.16,0.36,1.6,45.7,FW
49,Maximilian Beier,0.6,1.5,3.0,0.20,0.41,0.4,0.4,20.0,Germany,...,0.0,0.4,0.4,0.0,3.0,0.20,0.41,1.5,47.6,FWMF

In [8]:
df_2.drop(columns=['Rk','Season', 'FK', '-9999'], inplace=True)
df_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 8365 entries, 0 to 8364
Data columns (total 34 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Player     8365 non-null   str
 1   Min        8365 non-null   int64
 2   SoT/90     8365 non-null   float64
 3   Sh/90      8365 non-null   float64
 4   G/Sh       8365 non-null   float64
 5   G/SoT      8365 non-null   float64
 6   TklW/90    8365 non-null   float64
 7   Int/90     8365 non-null   float64
 8   Age        8345 non-null   float64
 9   Nation     8299 non-null   str
 10  Team       8365 non-null   str
 11  Comp       8365 non-null   str
 12  MP         8365 non-null   int64
 13  Min.1      8365 non-null   int64
 14  90s        8365 non-null   float64
 15  Starts     8365 non-null   int64
 16  Subs       8365 non-null   int64
 17  unSub      8365 non-null   int64
 18  Gls        8365 non-null   float64
 19  Ast        8365 non-null   float64
 20  G+A        8365 non-null   float64
 21  G-PK       8365 non-null   float64
 22  PK         8365 non-null   float64
 23  PKatt      8365 non-null   float64
 24  PKm        8365 non-null   float64
 25  TklW/90.1  8365 non-null   float64
 26  Int/90.1   8365 non-null   float64
 27  Tkl+Int    8365 non-null   float64
 28  Sh/90.1    8365 non-null   float64
 29  G/Sh.1     8365 non-null   float64
 30  G/SoT.1    8365 non-null   float64
 31  SoT/90.1   8365 non-null   float64
 32  SoT%       8365 non-null   float64
 33  Pos        8365 non-null   str
dtypes: float64(23), int64(6), str(5)
memory usage: 2.2 MB

In [9]:
df_2.head(50)

,Player,Min,SoT/90,Sh/90,G/Sh,G/SoT,TklW/90,Int/90,Age,Nation,...,PKm,TklW/90.1,Int/90.1,Tkl+Int,Sh/90.1,G/Sh.1,G/SoT.1,SoT/90.1,SoT%,Pos
0,James Wilson,4140,0.1,0.3,0.14,0.40,1.3,1.9,35.0,Wales,...,0.0,1.3,1.9,0.0,0.3,0.14,0.40,0.1,35.7,DF
1,Sean Roughan,4140,0.1,0.4,0.06,0.17,1.0,1.0,20.0,Republic of Ireland,...,0.0,1.0,1.0,0.0,0.4,0.06,0.17,0.1,33.3,DF
2,Zak Vyner,4140,0.0,0.3,0.07,1.00,1.1,0.9,27.0,Kenya,...,0.0,1.1,0.9,0.0,0.3,0.07,1.00,0.0,6.7,DF
3,Jason Knight,4140,0.2,1.1,0.06,0.33,0.9,1.0,23.0,Republic of Ireland,...,0.0,0.9,1.0,0.0,1.1,0.06,0.33,0.2,18.4,MF
4,Lewis Wing,4140,0.5,2.0,0.10,0.38,1.8,1.0,29.0,England,...,0.0,1.8,1.0,0.0,2.0,0.10,0.38,0.5,26.1,MF
5,Dominic Hyam,4140,0.1,0.5,0.10,0.67,0.6,0.6,28.0,Scotland,...,0.0,0.6,0.6,0.0,0.5,0.10,0.67,0.1,14.3,DF
6,Joe Rodon,4135,0.0,0.5,0.05,0.50,0.5,0.7,26.0,Wales,...,0.0,0.5,0.7,0.0,0.5,0.05,0.50,0.0,9.5,DF
7,Owen Bailey,4123,0.3,1.2,0.09,0.36,0.9,0.8,25.0,England,...,0.0,0.9,0.8,0.0,1.2,0.09,0.36,0.3,26.4,MFDF
8,Josh Neufville,4059,0.3,0.8,0.11,0.33,1.1,0.7,24.0,England,...,0.0,1.1,0.7,0.0,0.8,0.11,0.33,0.3,31.6,MF
9,Will Wright,4057,0.3,0.8,0.16,0.40,0.8,1.0,27.0,England,...,0.0,0.8,1.0,0.0,0.8,0.16,0.40,0.3,39.5,DF
10,Maxime Estève,4055,0.0,0.2,0.14,1.00,0.6,0.9,22.0,France,...,0.0,0.6,0.9,0.0,0.2,0.14,1.00,0.0,14.3,DF
11,Jimmy Dunne,4050,0.4,1.2,0.09,0.26,1.6,1.0,26.0,Republic of Ireland,...,0.0,1.6,1.0,0.0,1.2,0.09,0.26,0.4,34.5,DF
12,Paul Nardi,4050,0.0,0.0,0.00,0.00,0.0,0.0,30.0,France,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,100.0,GK
13,Anthony O'Connor,4050,0.1,0.5,0.04,0.20,0.8,1.4,31.0,Republic of Ireland,...,0.0,0.8,1.4,0.0,0.5,0.04,0.20,0.1,21.7,DF
14,Matthew Platt,4050,0.2,0.4,0.11,0.29,1.0,0.8,26.0,England,...,0.0,1.0,0.8,0.0,0.4,0.11,0.29,0.2,36.8,DF
15,Shane Duffy,4040,0.2,0.8,0.11,0.44,0.4,0.7,32.0,Republic of Ireland,...,0.0,0.4,0.7,0.0,0.8,0.11,0.44,0.2,25.0,DF
16,Ben Cabango,4032,0.1,0.5,0.09,0.40,1.3,0.9,24.0,Wales,...,0.0,1.3,0.9,0.0,0.5,0.09,0.40,0.1,21.7,DF
17,Connor Ogilvie,4028,0.2,0.9,0.10,0.44,0.6,1.4,28.0,England,...,0.0,0.6,1.4,0.0,0.9,0.10,0.44,0.2,23.1,DF
18,Milan van Ewijk,4010,0.2,0.7,0.07,0.25,1.6,1.3,23.0,Netherlands,...,0.0,1.6,1.3,0.0,0.7,0.07,0.25,0.2,27.6,DFMF
19,Torbjørn Heggem,4010,0.1,0.6,0.04,0.17,1.1,0.7,25.0,Norway,...,0.0,1.1,0.7,0.0,0.6,0.04,0.17,0.1,23.1,DF
20,Alistair Smith,4006,0.5,1.4,0.10,0.29,1.1,0.7,30.0,Scotland,...,0.0,1.1,0.7,0.0,1.4,0.10,0.29,0.5,33.9,MF
21,Matt Grimes,3976,0.2,0.6,0.11,0.33,1.0,0.8,29.0,England,...,0.0,1.0,0.8,0.0,0.6,0.11,0.33,0.2,32.1,MF
22,Joe Powell,3964,0.2,1.4,0.02,0.09,1.0,1.0,25.0,England,...,0.0,1.0,1.0,0.0,1.4,0.02,0.09,0.2,17.7,MF
23,Jason Kerr,3960,0.1,0.4,0.06,0.33,0.5,1.4,27.0,Scotland,...,0.0,0.5,1.4,0.0,0.4,0.06,0.33,0.1,17.6,DF
24,Connor Hall,3956,0.2,0.8,0.00,0.00,1.0,1.3,31.0,England,...,0.0,1.0,1.3,0.0,0.8,0.00,0.00,0.2,25.7,DF
25,Taylor Allen,3952,0.5,1.3,0.14,0.35,0.7,0.9,24.0,England,...,0.0,0.7,0.9,0.0,1.3,0.14,0.35,0.5,41.1,DF
26,Carl Piergianni,3949,0.2,1.0,0.07,0.30,0.9,0.8,32.0,England,...,0.0,0.9,0.8,0.0,1.0,0.07,0.30,0.2,23.3,DF
27,Ellis Iandolo,3948,0.2,0.7,0.03,0.10,1.2,1.3,26.0,England,...,0.0,1.2,1.3,0.0,0.7,0.03,0.10,0.2,33.3,DF
28,Tyler Bindon,3942,0.2,0.5,0.09,0.25,0.6,1.0,19.0,New Zealand,...,0.0,0.6,1.0,0.0,0.5,0.09,0.25,0.2,34.8,DF
29,Josh Tymon,3940,0.2,0.5,0.08,0.20,0.6,1.4,25.0,England,...,0.0,0.6,1.4,0.0,0.5,0.08,0.20,0.2,41.7,DF
30,Hakeem Odoffin,3936,0.3,1.1,0.10,0.36,1.2,1.7,26.0,England,...,0.0,1.2,1.7,0.0,1.1,0.10,0.36,0.3,28.0,DFMF
31,Luke O'Nien,3934,0.1,0.4,0.18,0.50,0.7,1.0,29.0,England,...,0.0,0.7,1.0,0.0,0.4,0.18,0.50,0.1,35.3,DF
32,Mitchell Pinnock,3924,0.3,1.0,0.05,0.18,0.9,1.0,29.0,England,...,0.0,0.9,1.0,0.0,1.0,0.05,0.18,0.3,25.6,MF
33,Jordan Turnbull,3920,0.0,0.4,0.06,1.00,1.0,1.6,29.0,England,...,0.0,1.0,1.6,0.0,0.4,0.06,1.00,0.0,6.3,DF
34,Jacob Bedeau,3903,0.1,0.3,0.00,0.00,1.2,0.8,24.0,Grenada,...,0.0,1.2,0.8,0.0,0.3,0.00,0.00,0.1,27.3,DF
35,Macaulay Gillesphey,3881,0.2,0.4,0.26,0.50,1.2,1.2,28.0,England,...,0.0,1.2,1.2,0.0,0.4,0.26,0.50,0.2,52.6,DF
36,Dan Neil,3877,0.1,0.6,0.08,0.40,1.2,1.1,22.0,England,...,0.0,1.2,1.1,0.0,0.6,0.08,0.40,0.1,20.8,MF
37,Liam Gordon,3872,0.3,1.0,0.07,0.25,1.1,0.7,25.0,Guyana,...,0.0,1.1,0.7,0.0,1.0,0.07,0.25,0.3,29.3,MF
38,Callum Whelan,3870,0.1,0.4,0.11,0.33,0.4,0.4,25.0,England,...,0.0,0.4,0.4,0.0,0.4,0.11,0.33,0.1,31.6,MFFW
39,Jamie Stott,3868,0.2,0.4,0.16,0.33,0.9,0.9,26.0,England,...,0.0,0.9,0.9,0.0,0.4,0.16,0.33,0.2,47.4,DF
40,Ben Jackson,3857,0.3,1.2,0.02,0.08,1.1,0.6,23.0,England,...,0.0,1.1,0.6,0.0,1.2,0.02,0.08,0.3,26.0,DFMF
41,Jayden Bogle,3824,0.3,1.1,0.13,0.43,1.7,0.9,24.0,England,...,0.0,1.7,0.9,0.0,1.1,0.13,0.43,0.3,29.8,DF
42,Tendayi Darikwa,3819,0.2,0.7,0.17,0.56,1.0,1.4,32.0,Zimbabwe,...,0.0,1.0,1.4,0.0,0.7,0.17,0.56,0.2,30.0,MFDF
43,Harvey Rodgers,3817,0.3,0.7,0.13,0.36,0.5,1.7,27.0,England,...,0.0,0.5,1.7,0.0,0.7,0.13,0.36,0.3,36.7,DF
44,Matthew Pollock,3815,0.2,0.6,0.07,0.25,0.8,1.4,22.0,England,...,0.0,0.8,1.4,0.0,0.6,0.07,0.25,0.2,29.6,DF
45,Oliver Casey,3814,0.2,0.7,0.11,0.33,1.0,1.7,23.0,England,...,0.0,1.0,1.7,0.0,0.7,0.11,0.33,0.2,32.1,DF
46,Christoph Klarer,3813,0.1,0.3,0.07,0.33,1.0,0.8,24.0,Austria,...,0.0,1.0,0.8,0.0,0.3,0.07,0.33,0.1,21.4,DF
47,Trai Hume,3810,0.2,0.7,0.10,0.33,1.8,1.2,22.0,Northern Ireland,...,0.0,1.8,1.2,0.0,0.7,0.10,0.33,0.2,30.0,DF
48,Conor Coventry,3810,0.1,0.6,0.04,0.17,2.2,1.6,24.0,Republic of Ireland,...,0.0,2.2,1.6,0.0,0.6,0.04,0.17,0.1,25.0,MF
49,Josh Cullen,3801,0.2,0.6,0.08,0.25,0.8,0.8,28.0,Republic of Ireland,...,0.0,0.8,0.8,0.0,0.6,0.08,0.25,0.2,33.3,MF

In [10]:
# Merge the two dataframes together - leave non numeric columns as they are, 
# average numeric columns for names that appear in both dataframes.
# Append lone entries from either dataframe.

# Identify the key column (typically 'Player' or 'Name')
key_col = 'Player' if 'Player' in df_1.columns else 'Name'

# Identify numeric and non-numeric columns (excluding the key)
numeric_cols = df_1.select_dtypes(include=[np.number]).columns.tolist()
non_numeric_cols = df_1.select_dtypes(exclude=[np.number]).columns.tolist()

# Remove the key column from non-numeric list if present
if key_col in non_numeric_cols:
    non_numeric_cols.remove(key_col)

print(f"Key column: {key_col}")
print(f"Numeric columns ({len(numeric_cols)}): {numeric_cols[:5]}...")
print(f"Non-numeric columns ({len(non_numeric_cols)}): {non_numeric_cols[:5]}...")

# Separate players into three groups
players_df1 = set(df_1[key_col].unique())
players_df2 = set(df_2[key_col].unique())

common_players = players_df1 & players_df2
only_df1 = players_df1 - players_df2
only_df2 = players_df2 - players_df1

print(f"\nPlayers in both dataframes: {len(common_players)}")
print(f"Players only in df_1: {len(only_df1)}")
print(f"Players only in df_2: {len(only_df2)}")

# For common players: average numeric columns, keep non-numeric from df_1
common_df1 = df_1[df_1[key_col].isin(common_players)].copy()
common_df2 = df_2[df_2[key_col].isin(common_players)].copy()

# Merge and average numeric columns
merged_common = common_df1[[key_col] + non_numeric_cols].copy()

for col in numeric_cols:
    # Create a temporary merge to align the data
    temp_merge = common_df1[[key_col, col]].merge(
        common_df2[[key_col, col]], 
        on=key_col, 
        how='inner',
        suffixes=('_1', '_2')
    )
    # Calculate average
    merged_common[col] = temp_merge[[f'{col}_1', f'{col}_2']].mean(axis=1).values

# Get lone entries from df_1 and df_2
lone_df1 = df_1[df_1[key_col].isin(only_df1)].copy()
lone_df2 = df_2[df_2[key_col].isin(only_df2)].copy()

# Combine all three groups
df_merged = pd.concat([merged_common, lone_df1, lone_df2], ignore_index=True)

print(f"\nMerged dataframe shape: {df_merged.shape}")
print(f"Total unique players: {df_merged[key_col].nunique()}")

df_merged.head(10)

Key column: Player
Numeric columns (29): ['Gls/90', 'SoT/90', 'Sh/90', 'G/Sh', 'G/SoT']...
Non-numeric columns (4): ['Nation', 'Team', 'Comp', 'Pos']...

Players in both dataframes: 4682
Players only in df_1: 2463
Players only in df_2: 3647

KeyError: "['Gls/90'] not in index"