In [1]:
#%pip install matplotlib numpy pandas
import matplotlib.pyplot as plt 
import numpy as np 
import pandas as pd

In [2]:
df_1 = pd.read_csv('../fbref_2023-2024_Domestic_Leagues_stats.csv')

df_2 = pd.read_csv('../fbref_2024_2025_Domestic_League_stats copy.csv')

In [3]:
df_1.head(25)

,Rk,Player,Gls/90,SoT/90,Sh/90,G/Sh,G/SoT,TklW/90,Int/90,Season,...,Int/90.1,Tkl+Int,Sh/90.1,G/Sh.1,G/SoT.1,SoT/90.1,SoT%,FK,Pos,-9999
0,1,Macaulay Langstaff,0.6,1.5,3.8,0.14,0.35,0.2,0.2,2023-2024,...,0.2,0.0,3.8,0.14,0.35,1.5,40.1,NaN,FWMF,ca9b48af
1,2,Sammie Szmodics,0.6,1.4,3.3,0.19,0.46,0.4,0.4,2023-2024,...,0.4,0.0,3.3,0.19,0.46,1.4,41.3,NaN,MFFW,39944392
2,3,Matt Smith,0.6,1.4,3.1,0.20,0.43,0.1,0.1,2023-2024,...,0.1,0.0,3.1,0.20,0.43,1.4,45.5,NaN,FW,2d44ca9b
3,4,Alfie May,0.6,1.4,3.7,0.12,0.32,0.4,0.1,2023-2024,...,0.1,0.0,3.7,0.12,0.32,1.4,36.8,NaN,FWMF,992453d1
4,5,Davis Keillor-Dunn,0.6,1.8,4.3,0.13,0.33,0.9,0.6,2023-2024,...,0.6,0.0,4.3,0.13,0.33,1.8,41.1,NaN,MFFW,41d05caa
5,6,Kévin Denkey,0.7,1.5,4.2,0.15,0.43,0.4,0.1,2023-2024,...,0.1,0.0,4.2,0.15,0.43,1.5,35.4,NaN,FW,0d3585b5
6,7,Martin Braithwaite,0.6,1.2,3.0,0.14,0.35,0.3,0.1,2023-2024,...,0.1,0.0,3.0,0.14,0.35,1.2,39.1,NaN,FW,fd771f95
7,8,Henk Veerman,0.6,1.4,3.0,0.18,0.40,0.2,0.1,2023-2024,...,0.1,0.0,3.0,0.18,0.40,1.4,45.5,NaN,FW,e1a1b481
8,9,Lawrence Shankland,0.7,1.4,3.8,0.15,0.42,0.3,0.1,2023-2024,...,0.1,0.0,3.8,0.15,0.42,1.4,36.8,NaN,FW,63b1a176
9,10,Alexandre Mendy,0.6,1.3,2.8,0.17,0.36,0.1,0.2,2023-2024,...,0.2,0.0,2.8,0.17,0.36,1.3,47.5,NaN,FW,e067808c
10,11,Paul Mullin,0.7,1.6,3.4,0.18,0.38,0.5,0.2,2023-2024,...,0.2,0.0,3.4,0.18,0.38,1.6,47.3,NaN,FW,e7ef2c4e
11,12,Vangelis Pavlidis,0.9,1.9,3.6,0.23,0.45,0.6,0.1,2023-2024,...,0.1,0.0,3.6,0.23,0.45,1.9,51.2,NaN,FW,d578db11
12,13,Milan Smit,0.6,1.3,2.7,0.12,0.26,0.8,0.3,2023-2024,...,0.3,0.0,2.7,0.12,0.26,1.3,47.8,NaN,FWMF,a61ff812
13,14,Anders Dreyer,0.6,1.3,2.9,0.17,0.37,0.4,0.3,2023-2024,...,0.3,0.0,2.9,0.17,0.37,1.3,45.3,NaN,FWMF,c6486b01
14,15,Viktor Gyökeres,0.9,1.8,3.5,0.21,0.41,0.3,0.2,2023-2024,...,0.2,0.0,3.5,0.21,0.41,1.8,51.3,NaN,FW,4d5a9185
15,16,Phil Foden,0.6,1.5,3.3,0.18,0.40,0.6,0.4,2023-2024,...,0.4,0.0,3.3,0.18,0.40,1.5,45.7,NaN,MF,ed1e53f3
16,17,Mauro Icardi,0.8,1.6,3.5,0.17,0.38,0.1,0.1,2023-2024,...,0.1,0.0,3.5,0.17,0.38,1.6,44.6,NaN,FW,43b78598
17,18,Isaac Olaofe,0.6,1.0,2.2,0.29,0.61,0.5,0.1,2023-2024,...,0.1,0.0,2.2,0.29,0.61,1.0,48.5,NaN,FW,2f4fb18c
18,19,Harry Kane,1.1,2.1,4.6,0.21,0.46,0.3,0.3,2023-2024,...,0.3,0.0,4.6,0.21,0.46,2.1,45.9,NaN,FW,21a66f6a
19,20,Philip Otele,0.6,1.6,3.2,0.18,0.37,0.7,0.6,2023-2024,...,0.6,0.0,3.2,0.18,0.37,1.6,49.0,NaN,FWMF,d3655d19
20,21,Peque,0.6,1.1,2.2,0.14,0.28,1.1,0.3,2023-2024,...,0.3,0.0,2.2,0.14,0.28,1.1,52.2,NaN,MF,cb971b4f
21,22,Gennaro Tutino,0.6,1.3,2.9,0.18,0.41,0.1,0.0,2023-2024,...,0.0,0.0,2.9,0.18,0.41,1.3,42.9,NaN,FWMF,8b303bcb
22,23,Luuk de Jong,0.9,2.1,4.7,0.16,0.37,0.5,0.1,2023-2024,...,0.1,0.0,4.7,0.16,0.37,2.1,43.4,NaN,FW,abb3bb95
23,24,Robert Lewandowski,0.6,1.4,3.0,0.16,0.35,0.1,0.3,2023-2024,...,0.3,0.0,3.0,0.16,0.35,1.4,46.2,NaN,FW,8d78e732
24,25,Edin Džeko,0.7,2.1,4.9,0.13,0.30,0.4,0.1,2023-2024,...,0.1,0.0,4.9,0.13,0.30,2.1,43.5,NaN,FW,3bb7f478

In [4]:
df_2.head(25)

,Rk,Player,Gls/90,SoT/90,Sh/90,TklW/90,Int/90,Tkl+Int/90,G/Sh,G/SoT,...,Int,Tkl+Int,Sh,G/Sh.1,G/SoT.1,SoT,SoT%.1,FK,Pos,-9999
0,1,Viktor Gyökeres,1.3,2.6,4.5,0.2,0.2,0.0,0.19,0.34,...,0.2,0.0,4.5,0.19,0.34,2.6,57.6,NaN,FW,4d5a9185
1,2,Alexander Sørloth,1.1,2.4,4.5,0.3,0.1,0.0,0.24,0.45,...,0.1,0.0,4.5,0.24,0.45,2.4,53.2,NaN,FW,e92cd3f7
2,3,Patrik Schick,1.1,1.8,3.6,0.3,0.2,0.0,0.29,0.59,...,0.2,0.0,3.6,0.29,0.59,1.8,50.0,NaN,FW,5d4f7d61
3,4,Ousmane Dembélé,1.1,2.7,5.0,0.3,0.5,0.0,0.21,0.39,...,0.5,0.0,5.0,0.21,0.39,2.7,52.6,NaN,FW,b19db005
4,5,Jan Kliment,1.1,1.5,2.8,0.4,0.2,0.0,0.27,0.52,...,0.2,0.0,2.8,0.27,0.52,1.5,52.1,NaN,FW,c2a30c01
5,6,Dániel Böde,1.0,1.7,3.5,0.1,0.2,0.0,0.25,0.54,...,0.2,0.0,3.5,0.25,0.54,1.7,47.1,NaN,FW,17f66244
6,7,Eli Junior Kroupi,1.0,1.8,4.0,0.4,0.5,0.0,0.20,0.45,...,0.5,0.0,4.0,0.20,0.45,1.8,44.2,NaN,FWMF,b2fe86e5
7,8,Davie Selke,1.0,2.0,3.9,0.1,0.1,0.0,0.23,0.44,...,0.1,0.0,3.9,0.23,0.44,2.0,51.2,NaN,FW,1238a3f9
8,9,Alaeddine Ajaraie,1.0,2.0,5.7,0.5,0.3,0.0,0.16,0.46,...,0.3,0.0,5.7,0.16,0.46,2.0,35.4,NaN,FWMF,f9182945
9,10,Victor Osimhen,1.0,2.2,5.2,0.2,0.3,0.0,0.15,0.35,...,0.3,0.0,5.2,0.15,0.35,2.2,41.6,NaN,FW,8c90fd7a
10,11,Harry Kane,1.0,2.0,4.3,0.4,0.2,0.0,0.15,0.31,...,0.2,0.0,4.3,0.15,0.31,2.0,47.4,NaN,FW,21a66f6a
11,12,Sambou Soumano,1.0,1.6,2.9,0.1,0.1,0.0,0.24,0.43,...,0.1,0.0,2.9,0.24,0.43,1.6,54.8,NaN,FW,7cc00776
12,13,Kylian Mbappé,1.0,2.6,5.0,0.2,0.0,0.0,0.15,0.28,...,0.0,0.0,5.0,0.15,0.28,2.6,52.8,NaN,FW,42fd9c7f
13,14,Mateo Retegui,0.9,1.4,3.9,0.4,0.1,0.0,0.20,0.55,...,0.1,0.0,3.9,0.20,0.55,1.4,36.5,NaN,FW,e7695e6c
14,15,Cherif Ndiaye,0.9,1.5,2.6,0.2,0.2,0.0,0.28,0.48,...,0.2,0.0,2.6,0.28,0.48,1.5,58.5,NaN,FW,858a54c3
15,16,Cristhian Stuani,0.9,1.6,2.8,0.6,0.7,0.0,0.24,0.42,...,0.7,0.0,2.8,0.24,0.42,1.6,55.9,NaN,FW,220c11f1
16,17,Aleksandar Katai,0.9,1.6,4.1,0.1,0.1,0.0,0.22,0.57,...,0.1,0.0,4.1,0.22,0.57,1.6,39.7,NaN,MFFW,d5127c3f
17,18,Oliver Edvardsen,0.9,1.3,3.2,0.8,0.6,0.0,0.29,0.71,...,0.6,0.0,3.2,0.29,0.71,1.3,40.5,NaN,MF,b54b05e2
18,19,Robert Lewandowski,0.9,1.6,3.9,0.2,0.1,0.0,0.21,0.50,...,0.1,0.0,3.9,0.21,0.50,1.6,41.7,NaN,FW,8d78e732
19,20,Saldanha,0.9,2.3,4.7,0.5,0.0,0.0,0.18,0.36,...,0.0,0.0,4.7,0.18,0.36,2.3,49.1,NaN,FWMF,88f39046
20,21,Youssef En-Nesyri,0.9,1.9,4.9,0.4,0.1,0.0,0.19,0.47,...,0.1,0.0,4.9,0.19,0.47,1.9,39.8,NaN,FW,04e17fd5
21,22,Efthimis Koulouris,0.9,1.7,3.4,0.2,0.2,0.0,0.21,0.41,...,0.2,0.0,3.4,0.21,0.41,1.7,50.9,NaN,FW,21f8d950
22,23,Myrto Uzuni,0.9,1.8,3.1,0.2,0.1,0.0,0.25,0.41,...,0.1,0.0,3.1,0.25,0.41,1.8,60.4,NaN,FW,01da7812
23,24,Marcos Leonardo,0.9,1.5,3.8,0.1,0.0,0.0,0.19,0.50,...,0.0,0.0,3.8,0.19,0.50,1.5,39.0,NaN,FW,3f47ebce
24,25,Aleksandar Mitrović,0.9,2.1,4.4,0.5,0.0,0.0,0.17,0.35,...,0.0,0.0,4.4,0.17,0.35,2.1,48.4,NaN,FW,3925dbd6

In [5]:
df_1.drop(columns=['Rk','Season', 'FK', '-9999'], inplace=True)
df_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 7170 entries, 0 to 7169
Data columns (total 34 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Player     7170 non-null   str
 1   Gls/90     7170 non-null   float64
 2   SoT/90     7170 non-null   float64
 3   Sh/90      7170 non-null   float64
 4   G/Sh       7170 non-null   float64
 5   G/SoT      7170 non-null   float64
 6   TklW/90    7170 non-null   float64
 7   Int/90     7170 non-null   float64
 8   Age        7166 non-null   float64
 9   Nation     7151 non-null   str
 10  Team       7170 non-null   str
 11  Comp       7170 non-null   str
 12  MP         7170 non-null   int64
 13  Min        7170 non-null   int64
 14  90s        7170 non-null   float64
 15  Starts     7170 non-null   int64
 16  Subs       7170 non-null   int64
 17  unSub      7170 non-null   int64
 18  Gls/90.1   7170 non-null   float64
 19  Ast        7170 non-null   float64
 20  G+A        7170 non-null   float64
 21  G-PK       7170 non-null   float64
 22  PK         7170 non-null   float64
 23  PKatt      7170 non-null   float64
 24  PKm        7170 non-null   float64
 25  TklW/90.1  7170 non-null   float64
 26  Int/90.1   7170 non-null   float64
 27  Tkl+Int    7170 non-null   float64
 28  Sh/90.1    7170 non-null   float64
 29  G/Sh.1     7170 non-null   float64
 30  G/SoT.1    7170 non-null   float64
 31  SoT/90.1   7170 non-null   float64
 32  SoT%       7170 non-null   float64
 33  Pos        7170 non-null   str
dtypes: float64(24), int64(5), str(5)
memory usage: 1.9 MB

In [6]:
# Clean up Nation column - convert codes like 'eng ENG' to 'England'
import re

# Extract the 3-letter country code (uppercase part) from Nation column
def clean_nation(nation_str):
    if pd.isna(nation_str):
        return nation_str
    # Extract the uppercase 3-letter code
    match = re.search(r'\b([A-Z]{3})\b', str(nation_str))
    code = match.group(1) if match else None
    
    if not code:
        return nation_str
    
    # Country code to name mapping (common FIFA/ISO codes)
    country_mapping = {
        'ENG': 'England', 'FRA': 'France', 'ESP': 'Spain', 'GER': 'Germany',
        'ITA': 'Italy', 'POR': 'Portugal', 'NED': 'Netherlands', 'BEL': 'Belgium',
        'ARG': 'Argentina', 'BRA': 'Brazil', 'URU': 'Uruguay', 'COL': 'Colombia',
        'CHI': 'Chile', 'MEX': 'Mexico', 'USA': 'United States', 'CAN': 'Canada',
        'CRO': 'Croatia', 'SRB': 'Serbia', 'SUI': 'Switzerland', 'AUT': 'Austria',
        'DEN': 'Denmark', 'SWE': 'Sweden', 'NOR': 'Norway', 'POL': 'Poland',
        'CZE': 'Czech Republic', 'SCO': 'Scotland', 'WAL': 'Wales', 'NIR': 'Northern Ireland',
        'IRL': 'Republic of Ireland', 'TUR': 'Turkey', 'GRE': 'Greece', 'UKR': 'Ukraine',
        'ROU': 'Romania', 'SVK': 'Slovakia', 'SVN': 'Slovenia', 'BUL': 'Bulgaria',
        'JPN': 'Japan', 'KOR': 'South Korea', 'AUS': 'Australia', 'NZL': 'New Zealand',
        'MAR': 'Morocco', 'SEN': 'Senegal', 'NGA': 'Nigeria', 'CIV': 'Ivory Coast',
        'GHA': 'Ghana', 'CMR': 'Cameroon', 'ALG': 'Algeria', 'TUN': 'Tunisia',
        'EGY': 'Egypt', 'RSA': 'South Africa', 'PAR': 'Paraguay', 'ECU': 'Ecuador',
        'VEN': 'Venezuela', 'PER': 'Peru', 'BOL': 'Bolivia', 'CRC': 'Costa Rica',
        'HON': 'Honduras', 'PAN': 'Panama', 'JAM': 'Jamaica', 'ISL': 'Iceland',
        'FIN': 'Finland', 'HUN': 'Hungary', 'BIH': 'Bosnia and Herzegovina',
        'MKD': 'North Macedonia', 'ALB': 'Albania', 'GEO': 'Georgia', 'ARM': 'Armenia',
        'ISR': 'Israel', 'CHN': 'China', 'IRN': 'Iran', 'KSA': 'Saudi Arabia',
        'QAT': 'Qatar', 'UAE': 'United Arab Emirates', 'IRQ': 'Iraq', 'UZB': 'Uzbekistan',
        'ATG': 'Antigua and Barbuda', 'BHR': 'Bahrain', 'BRN': 'Brunei', 'CYM': 'Cayman Islands',
        'DMA': 'Dominica', 'FRO': 'Faroe Islands', 'GIB': 'Gibraltar', 'GRL': 'Greenland', 'GUY': 'Guyana',
        'LIE': 'Liechtenstein', 'MDV': 'Maldives', 'MNE': 'Montenegro', 'MSR': 'Montserrat', 'NCL': 'New Caledonia',
        'PYF': 'French Polynesia', 'SMR': 'San Marino', 'TGO': 'Togo', 'TON': 'Tonga', 'VAT': 'Vatican City',
        'ANG': 'Angola', 'BDI': 'Burundi', 'BEN': 'Benin', 'BFA': 'Burkina Faso', 'CTA': 'Central African Republic',
        'CGO': 'Congo', 'COM': 'Comoros', 'DJI': 'Djibouti', 'ERI': 'Eritrea', 'ETH': 'Ethiopia',
        'GAB': 'Gabon', 'GMB': 'Gambia', 'GAM': 'Gambia', 'GIN': 'Guinea', 'GUI': 'Guinea', 'GNB': 'Guinea-Bissau', 'KEN': 'Kenya', 'LES': 'Lesotho', 'LBR': 'Liberia', 'MDV': 'Maldives',
        'MLI': 'Mali', 'MOZ': 'Mozambique', 'NAM': 'Namibia', 'NER': 'Niger', 'RWA': 'Rwanda',
        'SLE': 'Sierra Leone', 'SOM': 'Somalia', 'SSD': 'South Sudan', 'STP': 'Sao Tome and Principe', 
        'SWZ': 'Eswatini', 'TCD': 'Chad', 'TUN': 'Tunisia', 'UGA': 'Uganda', 'ZAM': 'Zambia', 'ZIM': 'Zimbabwe',
        'BLR': 'Belarus', 'BLZ': 'Belize', 'BOL': 'Bolivia', 'BOS': 'Bosnia and Herzegovina',
        'BEN': 'Benin', 'COD': 'DR Congo', 'BOE': 'Bonaire, Sint Eustatius and Saba', 'CUB': 'Cuba',
        'CPV': 'Cape Verde', 'DOM': 'Dominican Republic', 'GUF': 'French Guiana', 'CUW': 'Curacao', 
        'LBN': 'Lebanon', 'MYS': 'Malaysia', 'MDV': 'Maldives', 'MRT': 'Mauritania',
        'EST': 'Estonia', 'LTU': 'Lithuania', 'LVA': 'Latvia', 'RUS': 'Russia', 'CYP': 'Cyprus', 'LUX': 'Luxembourg', 'MDA': 'Moldova',
        'GRN': 'Grenada', 'GUA': 'Guatemala', 'HTI': 'Haiti', 'NIC': 'Nicaragua', 'IDN': 'Indonesia', 'IND': 'India', 'PAK': 'Pakistan', 'PHL': 'Philippines', 'THA': 'Thailand',
        'JOR': 'Jordan', 'KAZ': 'Kazakhstan', 'KGZ': 'Kyrgyzstan', 'LAO': 'Laos', 'LBN': 'Lebanon', 'MMR': 'Myanmar', 'NEP': 'Nepal', 'OMN': 'Oman',
        'KEN': 'Kenya', 'RWA': 'Rwanda', 'SLE': 'Sierra Leone', 'SOM': 'Somalia', 'SSD': 'South Sudan', 'STP': 'Sao Tome and Principe', 'LBY': 'Libya', 
        'SKN': 'Saint Kitts and Nevis', 'LCA': 'Saint Lucia', 'VCT': 'Saint Vincent and the Grenadines', 'SUR': 'Suriname', 'TTO': 'Trinidad and Tobago', 'TRI': 'Trinidad and Tobago',
        'LBR': 'Liberia', 'LIB': 'Lebanon', 'MAD': 'Madagascar', 'MLI': 'Mali', 'MOZ': 'Mozambique', 'NAM': 'Namibia', 'NER': 'Niger', 'RWA': 'Rwanda',
        'MTQ': 'Martinique', 'MUS': 'Mauritius', 'MYA': 'Myanmar', 'PYF': 'French Polynesia', 'REU': 'Reunion', 'SPM': 'Saint Pierre and Miquelon', 
        'VAN': 'Vanuatu', 'WSM': 'Samoa', 'YEM': 'Yemen', 'MSR': 'Montserrat', 'MLT': 'Malta', 'MAS': 'Malaysia', 'TOG': 'Togo', 'GLP': 'Guadeloupe',
        'EQG': 'Equatorial Guinea', 'HAI': 'Haiti', 'SRI': 'Sri Lanka', 'MTN': 'Mauritania', 'NIG': 'Niger', 'PHI': 'Phillipines', 'PLE': 'Palestine',
        'SDN': 'Sudan', 'SMA': 'Sint Maarten', 'CHA': 'Chad', 'TOG': 'Togo', 'VIE': 'Vietnam', 'KVX': 'Kosovo', 'AZE': 'Azerbaijan', 'BER': 'Bermuda', 'BAN': 'Bangladesh', 'FIJ': 'Fiji',
        'TAN': 'Tanzania', 'SYR': 'Syria', 'TCH': 'Czechia', 'MWI': 'Malawi', 'BRB': 'Barbados'
    } 
    
    return country_mapping.get(code, nation_str)

# Apply to dataframe
if 'Nation' in df_1.columns:
    df_1['Nation'] = df_1['Nation'].apply(clean_nation)

if 'Nation' in df_2.columns:
    df_2['Nation'] = df_2['Nation'].apply(clean_nation)

print("Nation column cleaned successfully!")
print("\nSample values from df_1:")
print(df_1['Nation'].value_counts().head(10))

Nation column cleaned successfully!

Sample values from df_1:
Nation
England        832
Spain          532
France         438
Netherlands    382
Italy          334
Germany        334
Brazil         235
Portugal       181
Belgium        167
Croatia        165
Name: count, dtype: int64

In [7]:
df_1.head(50)

,Player,Gls/90,SoT/90,Sh/90,G/Sh,G/SoT,TklW/90,Int/90,Age,Nation,...,PKm,TklW/90.1,Int/90.1,Tkl+Int,Sh/90.1,G/Sh.1,G/SoT.1,SoT/90.1,SoT%,Pos
0,Macaulay Langstaff,0.6,1.5,3.8,0.14,0.35,0.2,0.2,26.0,England,...,0.0,0.2,0.2,0.0,3.8,0.14,0.35,1.5,40.1,FWMF
1,Sammie Szmodics,0.6,1.4,3.3,0.19,0.46,0.4,0.4,27.0,Republic of Ireland,...,0.0,0.4,0.4,0.0,3.3,0.19,0.46,1.4,41.3,MFFW
2,Matt Smith,0.6,1.4,3.1,0.20,0.43,0.1,0.1,34.0,England,...,0.0,0.1,0.1,0.0,3.1,0.20,0.43,1.4,45.5,FW
3,Alfie May,0.6,1.4,3.7,0.12,0.32,0.4,0.1,30.0,England,...,0.0,0.4,0.1,0.0,3.7,0.12,0.32,1.4,36.8,FWMF
4,Davis Keillor-Dunn,0.6,1.8,4.3,0.13,0.33,0.9,0.6,25.0,England,...,0.0,0.9,0.6,0.0,4.3,0.13,0.33,1.8,41.1,MFFW
5,Kévin Denkey,0.7,1.5,4.2,0.15,0.43,0.4,0.1,22.0,Togo,...,0.0,0.4,0.1,0.0,4.2,0.15,0.43,1.5,35.4,FW
6,Martin Braithwaite,0.6,1.2,3.0,0.14,0.35,0.3,0.1,32.0,Denmark,...,0.0,0.3,0.1,0.0,3.0,0.14,0.35,1.2,39.1,FW
7,Henk Veerman,0.6,1.4,3.0,0.18,0.40,0.2,0.1,30.0,Netherlands,...,0.0,0.2,0.1,0.0,3.0,0.18,0.40,1.4,45.5,FW
8,Lawrence Shankland,0.7,1.4,3.8,0.15,0.42,0.3,0.1,27.0,Scotland,...,0.1,0.3,0.1,0.0,3.8,0.15,0.42,1.4,36.8,FW
9,Alexandre Mendy,0.6,1.3,2.8,0.17,0.36,0.1,0.2,29.0,Guinea-Bissau,...,0.0,0.1,0.2,0.0,2.8,0.17,0.36,1.3,47.5,FW
10,Paul Mullin,0.7,1.6,3.4,0.18,0.38,0.5,0.2,28.0,England,...,0.0,0.5,0.2,0.0,3.4,0.18,0.38,1.6,47.3,FW
11,Vangelis Pavlidis,0.9,1.9,3.6,0.23,0.45,0.6,0.1,24.0,Greece,...,0.0,0.6,0.1,0.0,3.6,0.23,0.45,1.9,51.2,FW
12,Milan Smit,0.6,1.3,2.7,0.12,0.26,0.8,0.3,20.0,Netherlands,...,0.0,0.8,0.3,0.0,2.7,0.12,0.26,1.3,47.8,FWMF
13,Anders Dreyer,0.6,1.3,2.9,0.17,0.37,0.4,0.3,25.0,Denmark,...,0.0,0.4,0.3,0.0,2.9,0.17,0.37,1.3,45.3,FWMF
14,Viktor Gyökeres,0.9,1.8,3.5,0.21,0.41,0.3,0.2,25.0,Sweden,...,0.0,0.3,0.2,0.0,3.5,0.21,0.41,1.8,51.3,FW
15,Phil Foden,0.6,1.5,3.3,0.18,0.40,0.6,0.4,23.0,England,...,0.0,0.6,0.4,0.0,3.3,0.18,0.40,1.5,45.7,MF
16,Mauro Icardi,0.8,1.6,3.5,0.17,0.38,0.1,0.1,30.0,Argentina,...,0.0,0.1,0.1,0.0,3.5,0.17,0.38,1.6,44.6,FW
17,Isaac Olaofe,0.6,1.0,2.2,0.29,0.61,0.5,0.1,23.0,England,...,0.0,0.5,0.1,0.0,2.2,0.29,0.61,1.0,48.5,FW
18,Harry Kane,1.1,2.1,4.6,0.21,0.46,0.3,0.3,30.0,England,...,0.0,0.3,0.3,0.0,4.6,0.21,0.46,2.1,45.9,FW
19,Philip Otele,0.6,1.6,3.2,0.18,0.37,0.7,0.6,24.0,Nigeria,...,0.0,0.7,0.6,0.0,3.2,0.18,0.37,1.6,49.0,FWMF
20,Peque,0.6,1.1,2.2,0.14,0.28,1.1,0.3,20.0,Spain,...,0.0,1.1,0.3,0.0,2.2,0.14,0.28,1.1,52.2,MF
21,Gennaro Tutino,0.6,1.3,2.9,0.18,0.41,0.1,0.0,26.0,Italy,...,0.0,0.1,0.0,0.0,2.9,0.18,0.41,1.3,42.9,FWMF
22,Luuk de Jong,0.9,2.1,4.7,0.16,0.37,0.5,0.1,32.0,Netherlands,...,0.1,0.5,0.1,0.0,4.7,0.16,0.37,2.1,43.4,FW
23,Robert Lewandowski,0.6,1.4,3.0,0.16,0.35,0.1,0.3,34.0,Poland,...,0.0,0.1,0.3,0.0,3.0,0.16,0.35,1.4,46.2,FW
24,Edin Džeko,0.7,2.1,4.9,0.13,0.30,0.4,0.1,37.0,Bosnia and Herzegovina,...,0.0,0.4,0.1,0.0,4.9,0.13,0.30,2.1,43.5,FW
25,Joel Pohjanpalo,0.7,1.4,3.2,0.19,0.43,0.2,0.1,28.0,Finland,...,0.0,0.2,0.1,0.0,3.2,0.19,0.43,1.4,44.2,FW
26,Loïs Openda,0.8,2.1,4.0,0.18,0.35,0.1,0.1,23.0,Belgium,...,0.0,0.1,0.1,0.0,4.0,0.18,0.35,2.1,51.2,FW
27,Krzysztof Piątek,0.6,1.5,3.4,0.13,0.30,0.3,0.2,28.0,Poland,...,0.0,0.3,0.2,0.0,3.4,0.13,0.30,1.5,43.6,FW
28,Fashion Sakala,0.6,1.4,3.5,0.16,0.40,0.4,0.2,26.0,Zambia,...,0.0,0.4,0.2,0.0,3.5,0.16,0.40,1.4,40.0,FWMF
29,Lautaro Martínez,0.8,1.6,3.7,0.20,0.47,0.5,0.6,25.0,Argentina,...,0.0,0.5,0.6,0.0,3.7,0.20,0.47,1.6,43.1,FW
30,Cristiano Ronaldo,1.2,2.4,6.2,0.15,0.38,0.2,0.0,38.0,Portugal,...,0.0,0.2,0.0,0.0,6.2,0.15,0.38,2.4,39.8,FW
31,Robert Glatzel,0.7,1.6,3.6,0.19,0.42,0.3,0.1,29.0,Germany,...,0.0,0.3,0.1,0.0,3.6,0.19,0.42,1.6,45.7,FW
32,Haris Tabakovic,0.7,1.6,3.2,0.19,0.38,0.2,0.1,29.0,Bosnia and Herzegovina,...,0.0,0.2,0.1,0.0,3.2,0.19,0.38,1.6,50.5,FW
33,Jonathan David,0.7,1.6,2.7,0.22,0.36,0.6,0.3,23.0,Canada,...,0.0,0.6,0.3,0.0,2.7,0.22,0.36,1.6,59.5,FW
34,Pierre-Emerick Aubameyang,0.6,1.8,4.0,0.11,0.25,0.5,0.3,34.0,Gabon,...,0.0,0.5,0.3,0.0,4.0,0.11,0.25,1.8,44.0,FW
35,Cole Palmer,0.8,1.6,3.7,0.12,0.28,0.4,0.7,21.0,England,...,0.0,0.4,0.7,0.0,3.7,0.12,0.28,1.6,42.6,MFFW
36,Artem Dovbyk,0.8,1.6,3.0,0.20,0.37,0.1,0.0,26.0,Ukraine,...,0.0,0.1,0.0,0.0,3.0,0.20,0.37,1.6,54.1,FW
37,Florinel Coman,0.6,2.4,4.2,0.12,0.22,0.3,0.2,25.0,Romania,...,0.0,0.3,0.2,0.0,4.2,0.12,0.22,2.4,56.2,FWMF
38,Erling Haaland,1.0,2.1,4.3,0.17,0.34,0.1,0.1,23.0,Norway,...,0.0,0.1,0.1,0.0,4.3,0.17,0.34,2.1,48.8,FWMF
39,Mohamed Salah,0.6,2.0,4.0,0.11,0.23,0.4,0.1,31.0,Egypt,...,0.1,0.4,0.1,0.0,4.0,0.11,0.23,2.0,49.1,FW
40,Rafa Mújica,0.7,1.9,4.2,0.17,0.38,0.5,0.2,24.0,Spain,...,0.0,0.5,0.2,0.0,4.2,0.17,0.38,1.9,44.9,FW
41,Thiago,0.6,1.1,2.8,0.15,0.38,0.7,0.2,22.0,Brazil,...,0.0,0.7,0.2,0.0,2.8,0.15,0.38,1.1,41.0,FW
42,Guillermo Martínez Ayala,0.6,1.3,3.0,0.17,0.38,0.1,0.0,28.0,Mexico,...,0.0,0.1,0.0,0.0,3.0,0.17,0.38,1.3,44.0,FW
43,Rey Manaj,0.6,1.5,4.1,0.12,0.33,0.3,0.1,26.0,Albania,...,0.0,0.3,0.1,0.0,4.1,0.12,0.33,1.5,36.8,FW
44,Firas Al-Buraikan,0.6,0.9,1.7,0.35,0.62,0.7,0.3,23.0,Saudi Arabia,...,0.0,0.7,0.3,0.0,1.7,0.35,0.62,0.9,56.5,FW
45,Paddy Madden,0.6,1.5,3.0,0.16,0.32,0.3,0.2,33.0,Republic of Ireland,...,0.0,0.3,0.2,0.0,3.0,0.16,0.32,1.5,50.0,FWMF
46,Alexander Sørloth,0.8,1.3,2.8,0.29,0.64,0.1,0.0,27.0,Norway,...,0.0,0.1,0.0,0.0,2.8,0.29,0.64,1.3,46.2,FW
47,Ante Budimir,0.6,1.3,2.8,0.18,0.40,0.5,0.2,32.0,Croatia,...,0.0,0.5,0.2,0.0,2.8,0.18,0.40,1.3,46.1,FW
48,Jeredy Hilterman,0.6,1.6,3.4,0.16,0.36,0.7,0.4,25.0,Suriname,...,0.0,0.7,0.4,0.0,3.4,0.16,0.36,1.6,45.7,FW
49,Maximilian Beier,0.6,1.5,3.0,0.20,0.41,0.4,0.4,20.0,Germany,...,0.0,0.4,0.4,0.0,3.0,0.20,0.41,1.5,47.6,FWMF

In [8]:
df_2.drop(columns=['Rk','Season', 'FK', '-9999'], inplace=True)
df_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 8165 entries, 0 to 8164
Data columns (total 36 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Player      8165 non-null   str
 1   Gls/90      8165 non-null   float64
 2   SoT/90      8165 non-null   float64
 3   Sh/90       8165 non-null   float64
 4   TklW/90     8165 non-null   float64
 5   Int/90      8165 non-null   float64
 6   Tkl+Int/90  8165 non-null   float64
 7   G/Sh        8165 non-null   float64
 8   G/SoT       8165 non-null   float64
 9   SoT%        8165 non-null   float64
 10  Age         8146 non-null   float64
 11  Nation      8104 non-null   str
 12  Team        8165 non-null   str
 13  Comp        8165 non-null   str
 14  MP          8165 non-null   int64
 15  Min         8165 non-null   int64
 16  90s         8165 non-null   float64
 17  Starts      8165 non-null   int64
 18  Subs        8165 non-null   int64
 19  unSub       8165 non-null   int64
 20  Gls         8165 non-null   float64
 21  Ast         8165 non-null   float64
 22  G+A         8165 non-null   float64
 23  G-PK        8165 non-null   float64
 24  PK          8165 non-null   float64
 25  PKatt       8165 non-null   float64
 26  PKm         8165 non-null   float64
 27  TklW        8165 non-null   float64
 28  Int         8165 non-null   float64
 29  Tkl+Int     8165 non-null   float64
 30  Sh          8165 non-null   float64
 31  G/Sh.1      8165 non-null   float64
 32  G/SoT.1     8165 non-null   float64
 33  SoT         8165 non-null   float64
 34  SoT%.1      8165 non-null   float64
 35  Pos         8165 non-null   str
dtypes: float64(26), int64(5), str(5)
memory usage: 2.2 MB

In [9]:
df_2.head(50)

,Player,Gls/90,SoT/90,Sh/90,TklW/90,Int/90,Tkl+Int/90,G/Sh,G/SoT,SoT%,...,PKm,TklW,Int,Tkl+Int,Sh,G/Sh.1,G/SoT.1,SoT,SoT%.1,Pos
0,Viktor Gyökeres,1.3,2.6,4.5,0.2,0.2,0.0,0.19,0.34,57.6,...,0.0,0.2,0.2,0.0,4.5,0.19,0.34,2.6,57.6,FW
1,Alexander Sørloth,1.1,2.4,4.5,0.3,0.1,0.0,0.24,0.45,53.2,...,0.0,0.3,0.1,0.0,4.5,0.24,0.45,2.4,53.2,FW
2,Patrik Schick,1.1,1.8,3.6,0.3,0.2,0.0,0.29,0.59,50.0,...,0.0,0.3,0.2,0.0,3.6,0.29,0.59,1.8,50.0,FW
3,Ousmane Dembélé,1.1,2.7,5.0,0.3,0.5,0.0,0.21,0.39,52.6,...,0.0,0.3,0.5,0.0,5.0,0.21,0.39,2.7,52.6,FW
4,Jan Kliment,1.1,1.5,2.8,0.4,0.2,0.0,0.27,0.52,52.1,...,0.0,0.4,0.2,0.0,2.8,0.27,0.52,1.5,52.1,FW
5,Dániel Böde,1.0,1.7,3.5,0.1,0.2,0.0,0.25,0.54,47.1,...,0.0,0.1,0.2,0.0,3.5,0.25,0.54,1.7,47.1,FW
6,Eli Junior Kroupi,1.0,1.8,4.0,0.4,0.5,0.0,0.20,0.45,44.2,...,0.0,0.4,0.5,0.0,4.0,0.20,0.45,1.8,44.2,FWMF
7,Davie Selke,1.0,2.0,3.9,0.1,0.1,0.0,0.23,0.44,51.2,...,0.0,0.1,0.1,0.0,3.9,0.23,0.44,2.0,51.2,FW
8,Alaeddine Ajaraie,1.0,2.0,5.7,0.5,0.3,0.0,0.16,0.46,35.4,...,0.1,0.5,0.3,0.0,5.7,0.16,0.46,2.0,35.4,FWMF
9,Victor Osimhen,1.0,2.2,5.2,0.2,0.3,0.0,0.15,0.35,41.6,...,0.0,0.2,0.3,0.0,5.2,0.15,0.35,2.2,41.6,FW
10,Harry Kane,1.0,2.0,4.3,0.4,0.2,0.0,0.15,0.31,47.4,...,0.0,0.4,0.2,0.0,4.3,0.15,0.31,2.0,47.4,FW
11,Sambou Soumano,1.0,1.6,2.9,0.1,0.1,0.0,0.24,0.43,54.8,...,0.0,0.1,0.1,0.0,2.9,0.24,0.43,1.6,54.8,FW
12,Kylian Mbappé,1.0,2.6,5.0,0.2,0.0,0.0,0.15,0.28,52.8,...,0.1,0.2,0.0,0.0,5.0,0.15,0.28,2.6,52.8,FW
13,Mateo Retegui,0.9,1.4,3.9,0.4,0.1,0.0,0.20,0.55,36.5,...,0.0,0.4,0.1,0.0,3.9,0.20,0.55,1.4,36.5,FW
14,Cherif Ndiaye,0.9,1.5,2.6,0.2,0.2,0.0,0.28,0.48,58.5,...,0.0,0.2,0.2,0.0,2.6,0.28,0.48,1.5,58.5,FW
15,Cristhian Stuani,0.9,1.6,2.8,0.6,0.7,0.0,0.24,0.42,55.9,...,0.0,0.6,0.7,0.0,2.8,0.24,0.42,1.6,55.9,FW
16,Aleksandar Katai,0.9,1.6,4.1,0.1,0.1,0.0,0.22,0.57,39.7,...,0.0,0.1,0.1,0.0,4.1,0.22,0.57,1.6,39.7,MFFW
17,Oliver Edvardsen,0.9,1.3,3.2,0.8,0.6,0.0,0.29,0.71,40.5,...,0.0,0.8,0.6,0.0,3.2,0.29,0.71,1.3,40.5,MF
18,Robert Lewandowski,0.9,1.6,3.9,0.2,0.1,0.0,0.21,0.50,41.7,...,0.0,0.2,0.1,0.0,3.9,0.21,0.50,1.6,41.7,FW
19,Saldanha,0.9,2.3,4.7,0.5,0.0,0.0,0.18,0.36,49.1,...,0.0,0.5,0.0,0.0,4.7,0.18,0.36,2.3,49.1,FWMF
20,Youssef En-Nesyri,0.9,1.9,4.9,0.4,0.1,0.0,0.19,0.47,39.8,...,0.0,0.4,0.1,0.0,4.9,0.19,0.47,1.9,39.8,FW
21,Efthimis Koulouris,0.9,1.7,3.4,0.2,0.2,0.0,0.21,0.41,50.9,...,0.0,0.2,0.2,0.0,3.4,0.21,0.41,1.7,50.9,FW
22,Myrto Uzuni,0.9,1.8,3.1,0.2,0.1,0.0,0.25,0.41,60.4,...,0.0,0.2,0.1,0.0,3.1,0.25,0.41,1.8,60.4,FW
23,Marcos Leonardo,0.9,1.5,3.8,0.1,0.0,0.0,0.19,0.50,39.0,...,0.0,0.1,0.0,0.0,3.8,0.19,0.50,1.5,39.0,FW
24,Aleksandar Mitrović,0.9,2.1,4.4,0.5,0.0,0.0,0.17,0.35,48.4,...,0.0,0.5,0.0,0.0,4.4,0.17,0.35,2.1,48.4,FW
25,Promise David,0.9,1.7,2.8,0.4,0.3,0.0,0.23,0.39,60.0,...,0.0,0.4,0.3,0.0,2.8,0.23,0.39,1.7,60.0,FW
26,Aleksandar Pešić,0.9,1.5,3.5,0.3,0.1,0.0,0.22,0.53,41.7,...,0.0,0.3,0.1,0.0,3.5,0.22,0.53,1.5,41.7,MFFW
27,Ayoze Pérez,0.9,1.4,3.4,0.6,0.3,0.0,0.25,0.61,41.3,...,0.0,0.6,0.3,0.0,3.4,0.25,0.61,1.4,41.3,FW
28,Adrian Segecic,0.9,1.9,4.1,1.1,0.2,0.0,0.21,0.45,47.5,...,0.0,1.1,0.2,0.0,4.1,0.21,0.45,1.9,47.5,MF
29,Mika Biereth,0.9,1.7,2.8,0.3,0.3,0.0,0.29,0.48,61.5,...,0.0,0.3,0.3,0.0,2.8,0.29,0.48,1.7,61.5,FW
30,Cristiano Ronaldo,0.9,2.3,5.1,0.0,0.1,0.0,0.11,0.25,45.6,...,0.0,0.0,0.1,0.0,5.1,0.11,0.25,2.3,45.6,FW
31,Paulinho,0.8,1.7,3.3,0.4,0.1,0.0,0.26,0.50,51.0,...,0.0,0.4,0.1,0.0,3.3,0.26,0.50,1.7,51.0,FW
32,Gonçalo Ramos,0.8,2.7,4.6,0.5,0.0,0.0,0.15,0.25,58.2,...,0.1,0.5,0.0,0.0,4.6,0.15,0.25,2.7,58.2,FW
33,Abderrazak Hamdallah,0.8,1.5,3.6,0.3,0.2,0.0,0.14,0.34,42.2,...,0.1,0.3,0.2,0.0,3.6,0.14,0.34,1.5,42.2,FW
34,Oihan Sancet,0.8,1.1,2.8,0.4,0.3,0.0,0.24,0.60,40.0,...,0.0,0.4,0.3,0.0,2.8,0.24,0.60,1.1,40.0,MF
35,Higinio Marín,0.8,2.3,3.7,0.4,0.1,0.0,0.10,0.16,62.5,...,0.0,0.4,0.1,0.0,3.7,0.10,0.16,2.3,62.5,FW
36,Benito Raman,0.8,2.4,3.5,0.5,0.1,0.0,0.23,0.34,67.9,...,0.0,0.5,0.1,0.0,3.5,0.23,0.34,2.4,67.9,FWMF
37,Ivan Toney,0.8,2.0,4.1,0.4,0.2,0.0,0.11,0.24,48.2,...,0.0,0.4,0.2,0.0,4.1,0.11,0.24,2.0,48.2,FW
38,Pedro,0.8,1.5,3.2,1.1,0.2,0.0,0.21,0.44,46.2,...,0.0,1.1,0.2,0.0,3.2,0.21,0.44,1.5,46.2,MFFW
39,Neyder Moreno,0.8,1.4,3.3,1.9,1.0,0.0,0.25,0.60,41.7,...,0.0,1.9,1.0,0.0,3.3,0.25,0.60,1.4,41.7,MF
40,Ferrán Torres,0.8,1.8,3.9,0.4,0.3,0.0,0.21,0.45,45.8,...,0.0,0.4,0.3,0.0,3.9,0.21,0.45,1.8,45.8,FWMF
41,Mexx Meerdink,0.8,1.7,3.7,0.4,0.2,0.0,0.22,0.47,46.3,...,0.0,0.4,0.2,0.0,3.7,0.22,0.47,1.7,46.3,FW
42,Wout Weghorst,0.8,1.5,2.9,0.2,0.1,0.0,0.25,0.50,50.0,...,0.1,0.2,0.1,0.0,2.9,0.25,0.50,1.5,50.0,FW
43,Philip Otele,0.8,2.0,3.3,0.5,0.4,0.0,0.24,0.41,59.5,...,0.0,0.5,0.4,0.0,3.3,0.24,0.41,2.0,59.5,MFFW
44,Lennart Mertens,0.8,1.7,3.0,0.3,0.1,0.0,0.27,0.48,55.6,...,0.0,0.3,0.1,0.0,3.0,0.27,0.48,1.7,55.6,FW
45,Ragnar Ache,0.8,2.4,4.8,0.2,0.1,0.0,0.17,0.33,49.5,...,0.0,0.2,0.1,0.0,4.8,0.17,0.33,2.4,49.5,FW
46,Bruno Duarte,0.8,1.7,3.0,0.2,0.2,0.0,0.24,0.44,54.8,...,0.0,0.2,0.2,0.0,3.0,0.24,0.44,1.7,54.8,FWMF
47,Sem Steijn,0.8,1.4,3.0,0.3,0.3,0.0,0.19,0.42,46.2,...,0.0,0.3,0.3,0.0,3.0,0.19,0.42,1.4,46.2,MF
48,Jáder Durán,0.8,1.9,4.3,0.7,0.1,0.0,0.18,0.41,45.1,...,0.0,0.7,0.1,0.0,4.3,0.18,0.41,1.9,45.1,FW
49,Myron Boadu,0.8,1.3,2.4,0.1,0.1,0.0,0.29,0.53,53.6,...,0.0,0.1,0.1,0.0,2.4,0.29,0.53,1.3,53.6,FW

In [10]:
# Merge the two dataframes together - leave non numeric columns as they are, 
# average numeric columns for names that appear in both dataframes.
# Append lone entries from either dataframe.


# Identify the key column (typically 'Player' or 'Name')
key_col = 'Player' if 'Player' in df_1.columns else 'Name'

# Identify numeric and non-numeric columns (excluding the key)
numeric_cols_df1 = df_1.select_dtypes(include=[np.number]).columns.tolist()
numeric_cols_df2 = df_2.select_dtypes(include=[np.number]).columns.tolist()

# Columns shared between both dataframes (safe to average)
shared_numeric_cols = sorted(set(numeric_cols_df1).intersection(numeric_cols_df2))

# Numeric columns present in only one dataframe (kept as-is)
df1_only_numeric_cols = sorted(set(numeric_cols_df1) - set(numeric_cols_df2))
df2_only_numeric_cols = sorted(set(numeric_cols_df2) - set(numeric_cols_df1))

non_numeric_cols = df_1.select_dtypes(exclude=[np.number]).columns.tolist()

# Remove the key column from non-numeric list if present
if key_col in non_numeric_cols:
    non_numeric_cols.remove(key_col)

print(f"Key column: {key_col}")
print(f"Shared numeric columns ({len(shared_numeric_cols)}): {shared_numeric_cols[:5]}...")
print(f"df_1-only numeric columns ({len(df1_only_numeric_cols)}): {df1_only_numeric_cols[:5]}...")
print(f"df_2-only numeric columns ({len(df2_only_numeric_cols)}): {df2_only_numeric_cols[:5]}...")
print(f"Non-numeric columns ({len(non_numeric_cols)}): {non_numeric_cols[:5]}...")

# Separate players into three groups
players_df1 = set(df_1[key_col].unique())
players_df2 = set(df_2[key_col].unique())

common_players = players_df1 & players_df2
only_df1 = players_df1 - players_df2
only_df2 = players_df2 - players_df1

print(f"\nPlayers in both dataframes: {len(common_players)}")
print(f"Players only in df_1: {len(only_df1)}")
print(f"Players only in df_2: {len(only_df2)}")

# For common players: average shared numeric columns, keep non-numeric from df_1
# First, remove duplicates by keeping the first occurrence of each player
common_df1 = df_1[df_1[key_col].isin(common_players)].drop_duplicates(subset=[key_col], keep='first').copy()
common_df2 = df_2[df_2[key_col].isin(common_players)].drop_duplicates(subset=[key_col], keep='first').copy()

# Build base from non-numeric columns in df_1
merged_common = common_df1[[key_col] + non_numeric_cols].copy()

# Set index so assignments align by player
common_df1_idx = common_df1.set_index(key_col)
common_df2_idx = common_df2.set_index(key_col)
merged_common = merged_common.set_index(key_col)

# Average shared numeric columns
for col in shared_numeric_cols:
    merged_common[col] = (common_df1_idx[col] + common_df2_idx[col]) / 2

# Keep season-specific numeric columns that only exist in one dataframe
for col in df1_only_numeric_cols:
    merged_common[col] = common_df1_idx[col]

for col in df2_only_numeric_cols:
    merged_common[col] = common_df2_idx[col]

# Restore key column as regular column
merged_common = merged_common.reset_index()

# Get lone entries from df_1 and df_2
lone_df1 = df_1[df_1[key_col].isin(only_df1)].copy()
lone_df2 = df_2[df_2[key_col].isin(only_df2)].copy()

# Combine all three groups
df_merged = pd.concat([merged_common, lone_df1, lone_df2], ignore_index=True, sort=False)

print(f"\nMerged dataframe shape: {df_merged.shape}")
print(f"Total unique players: {df_merged[key_col].nunique()}")

df_merged.head(10)

Key column: Player
Shared numeric columns (24): ['90s', 'Age', 'Ast', 'G+A', 'G-PK']...
df_1-only numeric columns (5): ['Gls/90.1', 'Int/90.1', 'Sh/90.1', 'SoT/90.1', 'TklW/90.1']...
df_2-only numeric columns (7): ['Gls', 'Int', 'Sh', 'SoT', 'SoT%.1']...
Non-numeric columns (4): ['Nation', 'Team', 'Comp', 'Pos']...

Players in both dataframes: 4575
Players only in df_1: 2570
Players only in df_2: 3557

Merged dataframe shape: (10713, 41)
Total unique players: 10702

,Player,Nation,Team,Comp,Pos,90s,Age,Ast,G+A,G-PK,...,Sh/90.1,SoT/90.1,TklW/90.1,Gls,Int,Sh,SoT,SoT%.1,Tkl+Int/90,TklW
0,Macaulay Langstaff,England,Notts County,eng League Two,FWMF,30.05,26.5,0.10,0.45,0.30,...,3.8,1.5,0.2,0.1,0.1,1.6,0.6,40.0,0.0,0.3
1,Sammie Szmodics,Republic of Ireland,Blackburn Rovers,eng Championship,MFFW,27.30,27.5,0.10,0.60,0.50,...,3.3,1.4,0.4,0.4,0.4,1.9,1.1,59.1,0.0,1.1
2,Alfie May,England,Charlton Athletic,eng League One,FWMF,32.25,30.5,0.15,0.75,0.50,...,3.7,1.4,0.4,0.6,0.2,2.7,1.3,47.1,0.0,0.4
3,Davis Keillor-Dunn,England,Mansfield Town,eng League Two,MFFW,39.85,25.5,0.15,0.65,0.50,...,4.3,1.8,0.9,0.4,0.3,2.5,1.0,40.6,0.0,0.5
4,Kévin Denkey,Togo,Cercle Brugge,be Belgian Pro League,FW,26.10,22.5,0.05,0.75,0.60,...,4.2,1.5,0.4,0.7,0.0,3.4,1.6,46.0,0.0,0.3
5,Henk Veerman,Netherlands,ADO Den Haag,nl Eerste Divisie,FW,35.30,30.5,0.20,0.90,0.60,...,3.0,1.4,0.2,0.8,0.1,3.2,1.4,43.9,0.0,0.2
6,Lawrence Shankland,Scotland,Hearts,sct Scottish Premiership,FW,32.35,27.5,0.20,0.70,0.45,...,3.8,1.4,0.3,0.3,0.3,3.3,1.1,32.6,0.0,0.5
7,Alexandre Mendy,Guinea-Bissau,Caen,fr Ligue 2,FW,32.15,29.5,0.05,0.50,0.35,...,2.8,1.3,0.1,0.3,0.1,2.9,1.1,37.3,0.0,0.4
8,Paul Mullin,England,Wrexham,eng League Two,FW,23.10,28.5,0.10,0.55,0.40,...,3.4,1.6,0.5,0.2,0.0,4.0,1.4,34.6,0.0,0.4
9,Vangelis Pavlidis,Greece,AZ Alkmaar,nl Eredivisie,FW,29.20,24.5,0.20,1.00,0.70,...,3.6,1.9,0.6,0.8,0.2,3.3,1.5,45.2,0.0,0.5

In [11]:
df_merged.info(verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 10713 entries, 0 to 10712
Data columns (total 41 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Player      10713 non-null  str
 1   Nation      10645 non-null  str
 2   Team        10713 non-null  str
 3   Comp        10713 non-null  str
 4   Pos         10713 non-null  str
 5   90s         10713 non-null  float64
 6   Age         10692 non-null  float64
 7   Ast         10713 non-null  float64
 8   G+A         10713 non-null  float64
 9   G-PK        10713 non-null  float64
 10  G/Sh        10713 non-null  float64
 11  G/Sh.1      10713 non-null  float64
 12  G/SoT       10713 non-null  float64
 13  G/SoT.1     10713 non-null  float64
 14  Gls/90      10713 non-null  float64
 15  Int/90      10713 non-null  float64
 16  MP          10713 non-null  float64
 17  Min         10713 non-null  float64
 18  PK          10713 non-null  float64
 19  PKatt       10713 non-null  float64
 20  PKm         10713 non-null  float64
 21  Sh/90       10713 non-null  float64
 22  SoT%        10713 non-null  float64
 23  SoT/90      10713 non-null  float64
 24  Starts      10713 non-null  float64
 25  Subs        10713 non-null  float64
 26  Tkl+Int     10713 non-null  float64
 27  TklW/90     10713 non-null  float64
 28  unSub       10713 non-null  float64
 29  Gls/90.1    7150 non-null   float64
 30  Int/90.1    7150 non-null   float64
 31  Sh/90.1     7150 non-null   float64
 32  SoT/90.1    7150 non-null   float64
 33  TklW/90.1   7150 non-null   float64
 34  Gls         8138 non-null   float64
 35  Int         8138 non-null   float64
 36  Sh          8138 non-null   float64
 37  SoT         8138 non-null   float64
 38  SoT%.1      8138 non-null   float64
 39  Tkl+Int/90  8138 non-null   float64
 40  TklW        8138 non-null   float64
dtypes: float64(36), str(5)
memory usage: 3.4 MB

In [13]:
 #show head of merged and all columns for first 100 rows
df_merged.head(100)

,Player,Nation,Team,Comp,Pos,90s,Age,Ast,G+A,G-PK,...,Sh/90.1,SoT/90.1,TklW/90.1,Gls,Int,Sh,SoT,SoT%.1,Tkl+Int/90,TklW
0,Macaulay Langstaff,England,Notts County,eng League Two,FWMF,30.05,26.5,0.10,0.45,0.30,...,3.8,1.5,0.2,0.1,0.1,1.6,0.6,40.0,0.0,0.3
1,Sammie Szmodics,Republic of Ireland,Blackburn Rovers,eng Championship,MFFW,27.30,27.5,0.10,0.60,0.50,...,3.3,1.4,0.4,0.4,0.4,1.9,1.1,59.1,0.0,1.1
2,Alfie May,England,Charlton Athletic,eng League One,FWMF,32.25,30.5,0.15,0.75,0.50,...,3.7,1.4,0.4,0.6,0.2,2.7,1.3,47.1,0.0,0.4
3,Davis Keillor-Dunn,England,Mansfield Town,eng League Two,MFFW,39.85,25.5,0.15,0.65,0.50,...,4.3,1.8,0.9,0.4,0.3,2.5,1.0,40.6,0.0,0.5
4,Kévin Denkey,Togo,Cercle Brugge,be Belgian Pro League,FW,26.10,22.5,0.05,0.75,0.60,...,4.2,1.5,0.4,0.7,0.0,3.4,1.6,46.0,0.0,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Ragnar Ache,Germany,Kaiserslautern,de 2. Bundesliga,FW,21.20,25.5,0.00,0.80,0.80,...,4.4,2.0,0.2,0.8,0.1,4.8,2.4,49.5,0.0,0.2
96,Donyell Malen,Netherlands,Dortmund,de Bundesliga,MFFW,15.00,24.5,0.05,0.65,0.65,...,3.6,1.8,0.4,0.6,0.3,3.3,1.5,44.1,0.0,0.4
97,Jamie Vardy,England,Leicester City,eng Championship,FW,25.50,36.5,0.10,0.70,0.50,...,3.0,1.6,0.2,0.3,0.2,1.8,0.8,44.8,0.0,0.4
98,Cherif Ndiaye,Senegal,2 Teams,2 Comps,FW,20.05,27.5,0.20,1.00,0.65,...,0.1,0.1,0.0,0.9,0.2,2.6,1.5,58.5,0.0,0.2
99,André-Pierre Gignac,France,UANL,mx Liga MX,FW,15.95,37.5,0.20,0.85,0.50,...,3.3,1.4,0.3,0.6,0.2,4.6,1.9,41.1,0.0,0.2

In [14]:
#Drop G/Sh.1, G/SoT.1, SoT%.1, Tkl+Int, Gls, Tkl+Int/90, SoT, Sh, TklW, Int
cols_to_drop = ['G/Sh.1', 'G/SoT.1', 'SoT%.1', 'Tkl+Int', 'Gls/90.1', 'Tkl+Int/90', 'SoT/90.1', 'Sh/90.1', 'TklW/90.1', 'Int/90.1', 'Gls/90.1', 'SoT/90.1', 'TklW' ]
df_merged.drop(columns=cols_to_drop, inplace=True)
df_merged.info(verbose=True)
df_merged.head(100)

<class 'pandas.DataFrame'>
RangeIndex: 10713 entries, 0 to 10712
Data columns (total 30 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Player   10713 non-null  str
 1   Nation   10645 non-null  str
 2   Team     10713 non-null  str
 3   Comp     10713 non-null  str
 4   Pos      10713 non-null  str
 5   90s      10713 non-null  float64
 6   Age      10692 non-null  float64
 7   Ast      10713 non-null  float64
 8   G+A      10713 non-null  float64
 9   G-PK     10713 non-null  float64
 10  G/Sh     10713 non-null  float64
 11  G/SoT    10713 non-null  float64
 12  Gls/90   10713 non-null  float64
 13  Int/90   10713 non-null  float64
 14  MP       10713 non-null  float64
 15  Min      10713 non-null  float64
 16  PK       10713 non-null  float64
 17  PKatt    10713 non-null  float64
 18  PKm      10713 non-null  float64
 19  Sh/90    10713 non-null  float64
 20  SoT%     10713 non-null  float64
 21  SoT/90   10713 non-null  float64
 22  Starts   10713 non-null  float64
 23  Subs     10713 non-null  float64
 24  TklW/90  10713 non-null  float64
 25  unSub    10713 non-null  float64
 26  Gls      8138 non-null   float64
 27  Int      8138 non-null   float64
 28  Sh       8138 non-null   float64
 29  SoT      8138 non-null   float64
dtypes: float64(25), str(5)
memory usage: 2.5 MB

,Player,Nation,Team,Comp,Pos,90s,Age,Ast,G+A,G-PK,...,SoT%,SoT/90,Starts,Subs,TklW/90,unSub,Gls,Int,Sh,SoT
0,Macaulay Langstaff,England,Notts County,eng League Two,FWMF,30.05,26.5,0.10,0.45,0.30,...,40.05,1.05,30.0,10.0,0.25,1.5,0.1,0.1,1.6,0.6
1,Sammie Szmodics,Republic of Ireland,Blackburn Rovers,eng Championship,MFFW,27.30,27.5,0.10,0.60,0.50,...,50.20,1.25,28.5,4.0,0.75,1.0,0.4,0.4,1.9,1.1
2,Alfie May,England,Charlton Athletic,eng League One,FWMF,32.25,30.5,0.15,0.75,0.50,...,41.95,1.35,33.5,10.0,0.40,1.0,0.6,0.2,2.7,1.3
3,Davis Keillor-Dunn,England,Mansfield Town,eng League Two,MFFW,39.85,25.5,0.15,0.65,0.50,...,40.85,1.40,42.5,3.0,0.70,0.0,0.4,0.3,2.5,1.0
4,Kévin Denkey,Togo,Cercle Brugge,be Belgian Pro League,FW,26.10,22.5,0.05,0.75,0.60,...,40.70,1.55,26.0,1.5,0.35,0.0,0.7,0.0,3.4,1.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Ragnar Ache,Germany,Kaiserslautern,de 2. Bundesliga,FW,21.20,25.5,0.00,0.80,0.80,...,47.15,2.20,23.0,5.0,0.20,0.0,0.8,0.1,4.8,2.4
96,Donyell Malen,Netherlands,Dortmund,de Bundesliga,MFFW,15.00,24.5,0.05,0.65,0.65,...,47.05,1.65,14.5,13.0,0.40,3.5,0.6,0.3,3.3,1.5
97,Jamie Vardy,England,Leicester City,eng Championship,FW,25.50,36.5,0.10,0.70,0.50,...,49.10,1.20,26.5,8.5,0.30,1.0,0.3,0.2,1.8,0.8
98,Cherif Ndiaye,Senegal,2 Teams,2 Comps,FW,20.05,27.5,0.20,1.00,0.65,...,79.25,0.80,21.5,8.0,0.10,2.0,0.9,0.2,2.6,1.5
99,André-Pierre Gignac,France,UANL,mx Liga MX,FW,15.95,37.5,0.20,0.85,0.50,...,42.45,1.65,17.0,5.0,0.25,1.0,0.6,0.2,4.6,1.9

In [15]:
df_merged.to_csv('../Fbref_Final_Data.csv')